### ISSUE TITLE
Filesystem in client side

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#100]
We would like an MTA style file system to client side. That would much more useful because of the following reasons:
-This file system worked in resource only. That means it can be created and read in the resource folder.
-It would be more important than JSON as we want to save different data types JSON would be a mess.

For example:
-If I create a /savepos command I wouldn't like to save it with the IC / OOC chatlog.
-Same as above if I want to save login username/password. It would be messy if it was in the same file where chatlog was.

Most of the players can understand simple file only. This file should be easily understandable and separated from the others. The players wouldn't be able to understan a block of files.

MTA functions: https://wiki.multitheftauto.com/wiki/Client_Scripting_Functions#File_functions

**Comment by 7Hazard** [comment]
There won't be a filesystem through client side scripting.
The only possible way to store data will be through 'alt.localData' Object that will only store a certain amount of data eg. 4 MB to start of with.
This local data feature will be implemented some time. An issue for that is more suited. This one will be closed.
