### ISSUE TITLE
[Bug] blip.remove (client side) sometimes crashes the game

### ISSUE THREAD

**Issue by yoranjj** [altmp/altv#104]
I tested this with and without reconnect and it seems to be random on both. Using **blip.remove()** in the new client sided blip api sometimes crashes the game, it's random and I can't pinpoint why this happens and when it happens. No minidumps get generated.

## Steps to Reproduce

1. Create a blip.
1. Delete the blip.
1. See if the game crashes.
1. Repeat if it doesn't.

## Code
```javascript
let blip = null;

alt.setInterval(() => {
    if (blip === null) {
        blip = new alt.PointBlip(0, 0, 80);

        blip.sprite = 108;
        blip.scale = 0.75;
        blip.color = 2;
    } else {
        blip.remove();
        blip = null;
    }
}, 500);
```

**Comment by yoranjj** [comment]
Forgot to add; no minidumps get generated

**Comment by emcifuntik** [comment]
Fixed in Build 595
