### ISSUE TITLE
[Bug] Fix loading bar when connecting to server

### ISSUE THREAD

**Issue by derRAV3N** [altmp/altv#107]
When connecting to a server, the bar is somewhere near full when first displayed, jumps to zero and from there fills. It should just be zero from the beginning.

## Expected Behavior
Bar should be empty from start and fill up to 100%

## Current Behavior
Bar is somewhere high, I guess 100%, then goes to low, probably 0%, then fills up normal. Probably related to some default being 100% or setting the max value after it being displayed and also it being animated (which I like!).

## Possible Solution
Maybe default value of the loading bar is set wrong?

## Steps to Reproduce
Connect to a server where you can load a few files.

## Context (Environment)
It's just generally not that beautiful, sorry for nitpicking.

**Comment by emcifuntik** [comment]
Fixed

**Comment by emcifuntik** [comment]
It shows progress of downloading for each script

**Comment by derRAV3N** [comment]
Is it not possible or not feasible to download the progress of the complete download? I think that would make more sense in most cases.
