### ISSUE TITLE
[Bug] gameEntityCreate executes gameEntityDestroy

### ISSUE THREAD

**Issue by Enerv** [altmp/altv#111]
I found an error that the event `gameEntityCreate` executes too `gameEntityDestroy`. I using client branch `#552` and server branch `#543`.

## Expected Behavior
Event `gameEntityCreate` not should triggered `gameEntityDestroy` event.

## Current Behavior
Event `gameEntityDestroy` working fine. Is called everytime a entity goes out of player's streaming range. Event `gameEntityCreate` is triggered when a car enters the stream zone and instantly called `gameEntityDestroy` event.

## Steps to Reproduce
1. Use this code.
1. Create a vehicle.
1. Check game console when events is triggered.
```js
alt.on('gameEntityCreate', (entity) => {
    alt.log(`gameEntityCreate: ${entity.model}`);
});

alt.on('gameEntityDestroy', (entity) => {
    alt.log(`gameEntityDestroy: ${entity.model}`);
});
```

**Comment by vadzz-dev** [comment]
Sorry im noob, xd
