### ISSUE TITLE
Avoid "F8 reconnect" in server.cfg

### ISSUE THREAD

**Issue by GangstaSunny** [altmp/altv#113]
**Describe the solution you'd like**
A simple "reconnect allow" / "reconnect disallow" to put in the server.cfg to allow (or not allow) players to reconnect with the command "reconnect" on the F8 clieny-console.

**Describe alternatives you've considered**
reconnect "block/unblock"
reconnect "on/off"
reconnect "yes/no"
reconnect "true/false"
...

**Comment by 7Hazard** [comment]
The reconnect feature is a temporary feature until disconnecting is properly working. You wouldn't want to disallow users from reconnecting via the alt:V menu when it's possible, would you?

**Comment by GangstaSunny** [comment]
Just thought this command will stay forever. If there would be no reconnect option via the F8 Console (or at least, not bugged) as soon as the first servers starts, it would be okay for me.

But if there is still a (bugged) reconnect option while some servers are already online, this option need to be implemented.

**Comment by FabianTerhorst** [comment]
It would be a problem when server beta would end with bugged reconnect and without an option.

**Comment by emcifuntik** [comment]
debug field added to server and client configs to control this.
