### ISSUE TITLE
Auto generating Documentation 

### ISSUE THREAD

**Issue by sriem** [altmp/altv#114]
**Is your feature request related to a problem? Please describe.**
The actual Documentation is almost not given. Many functions and fields are not known by the community.

**Describe the solution you'd like**
Get the Auto Documentation running ;)

**Comment by 7Hazard** [comment]
You have the altv-client.d.ts
It should contain all the functions. Is there anything thats missing there?

**Comment by sriem** [comment]
Its not about Clientside, its more about server, For example nobody knows whats inside the Base64 Data Strings. From the Vehicle Class.

**Comment by 7Hazard** [comment]
It's just all internal fields of the vehicle data, for example deformation data of the vehicle. That cannot be messed with and it's up to GTA to take care of and even we don't really know how to manipulate parts of them.
That is not relevant to the deocumentation though.

**Comment by sriem** [comment]
still, as long as we dont know which function we do have on server side what we can use we are just lost. And it takes a lot of work and time to play around and find out. Daylie there are new Features like vehicle.manualEngine, its not known everywhere but it exist. I do understand your point of yo, but understand also ours, we need the documentation, thats a fact, and not to see as a nice to have.

**Comment by 7Hazard** [comment]
I believe your issue lies with the corresponding module (NodeJS or C# module). This is an issue on their behalf. Report this to them. 
This issue is now considered to be about the online web documentation, that will be done in the near future.

For the time being all available functions can be known via the cpp-sdk and the client definitions.

**Comment by gamelaster** [comment]
:popcorn:

**Comment by FabianTerhorst** [comment]
Both js and c# modules have auto generated documentations available at https://altmp.github.io/altv-typings/ and https://fabianterhorst.github.io/coreclr-module/api/AltV.Net.html
