### ISSUE TITLE
add getNearestObjectOfType(EntityID, Distance)

### ISSUE THREAD

**Issue by sriem** [altmp/altv#115]
**Is your feature request related to a problem? Please describe.**
Please implement the function to get the nearest object of a certain type in front of a player 
e.g. ATM, Prop etc..

**Describe the solution you'd like**
function should return the found Entity or null

**Comment by DasChaosAT** [comment]
There is a native for that, `Object GET_CLOSEST_OBJECT_OF_TYPE(float x, float y, float z, float radius,
  Hash modelHash, BOOL isMission, BOOL p6, BOOL p7)
// 0xE143FA2249364369 0x45619B33`

so it should be possible to use it with game.getClosestObjectOfType()

**Comment by Stuyk** [comment]
Can be done through natives.
