### ISSUE TITLE
Switch altv rotation from radians to degrees

### ISSUE THREAD

**Issue by datWeazel** [altmp/altv#120]
**Is your feature request related to a problem? Please describe.**
Already existing collections of position-rotation informations are basically useless in altv since rotation information in altv is using radians while every other MP Mod and GTA V itself is using degrees.

**Describe the solution you'd like**
AltV should use degrees for rotation info.

**Comment by vadzz-dev** [comment]
1) GTA internally uses radians and just convert it for every call
2) radians are easily to use in calculations

So in general im against moving to degrees

**Comment by 7Hazard** [comment]
The module developers can provide conversion methods between radians and eular angles. No need for alt:V to implement it in the cpp-sdk.
