### ISSUE TITLE
Serverside "connectionComplete" event

### ISSUE THREAD

**Issue by datWeazel** [altmp/altv#122]
**Is your feature request related to a problem? Please describe.**
Currently there doesn't seem to be a "connectionComplete" event on serverside. Current workaround I'm using is a simple emitServer when the event is triggered on client side.

Don't know if this is just missing in C# or whatever ..

**Comment by FabianTerhorst** [comment]
c# implements all events

**Comment by Lhoerion** [comment]
Is it already fixed? Hard to actually deduce this

**Comment by FabianTerhorst** [comment]
There is no such event in cpp sdk. I also don't see a use case for this event. Feel free to comment when you have a reasonable use case for this event.
