### ISSUE TITLE
Sync walking styles 

### ISSUE THREAD

**Issue by datWeazel** [altmp/altv#123]
**Is your feature request related to a problem? Please describe.**
It seems like walking styles/movements clipsets set via `PED::SET_PED_MOVEMENT_CLIPSET` aren't synced and maybe even overridden somehow with the default walking style.

**Comment by FabianTerhorst** [comment]
Can you post the code you used to reproduce.

**Comment by datWeazel** [comment]
`var clipSet = "MOVE_M@DRUNK@VERYDRUNK";
game.setPedMovementClipset(player.scriptID, clipSet, 1.0);`

**Comment by emcifuntik** [comment]
Fixed
