### ISSUE TITLE
Support async function when you import from other resources

### ISSUE THREAD

**Issue by dictateurfou** [altmp/altv#127]
**Is your feature request related to a problem? Please describe.**

for any database or other thing that requires asynchronous function, if I want to use the database in another resource I am forced to duplicate the connection to the database. there is no solution to this problem because we can not import the connection object when we export it from a resource, otherwise it would be enough just to recreate the asynchronous function in each script.

**Additional context**
![Image of Gyazo](https://i.gyazo.com/1a61e6d172ec8860b3f2b96bf81495c2.png)

**Comment by FabianTerhorst** [comment]
Couldn't you notify the caller via a callback when the operation is finished. And build a promise out of the callback?

**Comment by dictateurfou** [comment]
no we can not export the connection object from a resource so I can not use the callback :/

**Comment by FabianTerhorst** [comment]
You can pass a own callback in your own exported function.

**Comment by dictateurfou** [comment]
I think I understood what you mean, in my resources instead of exporting a function asyncrhone rather export a function with a callback, I do not know if it will work being given that we can not import everything from a other resources but I will try

**Comment by FabianTerhorst** [comment]
I think thats the only chance you have because the resource import export api is not directly implemented for js, but for all modules e.g. c#, python, pawn. So its just mapped to the js api.

**Comment by dictateurfou** [comment]
I followed your advice and I managed to do what I wanted even if it is not the best solution it is the only valid, its better if this supported directly ^^
![Image of Gyazo](https://i.gyazo.com/136aa1d60ae7d291194b343080a0b315.png)

**Comment by 7Hazard** [comment]
No siiiiir.


Just await in the exported function.

**Comment by dictateurfou** [comment]
no sir
just await in the imported function , await in exported function work just return d'oesnt work
and no support await , no support promise , you support the minimum
async function is unusable in the state for use in external resources because ..... im have secret for you if you d'oesnt have await in async function for wait your result its useless
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/async_function

**Comment by FabianTerhorst** [comment]
I think you didn't understood how the resource import export is implemented in cpp. It's not a js implementation.

**Comment by dictateurfou** [comment]
and then it can improve no? it's still an important feature not necessarily necessary but it avoids doing callbacks everywhere.
promise is better

**Comment by FabianTerhorst** [comment]
You always have a overhead in resource <-> resource communication. Its recommend to build it into a single resource. You can still build a own resource system inside that. But its faster and shares the same memory.

**Comment by dictateurfou** [comment]
it's already what I intend to do with my core, but imagine that I want to do an admin resources or a utility but that would need the database and that I would not integrate in my core I could not use the async it's more to do small jobs I do not try to separate everything

**Comment by dictateurfou** [comment]
im have make test for performance between two resource and with one resource this time of execution is the same ...

**Comment by gamelaster** [comment]
Well actually, this is good idea, but I think it will be painful to implement it in our V8 resource system

**Comment by dictateurfou** [comment]
yes I understand, I do not ask for it for now, I know you probably have other priority, if you try and you can not it will not matter at least you'll try
