### ISSUE TITLE
Import All for NodeJS

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv#131]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. Its more of an ease of use thing. On the server-side we manually have to include each individual module we write. I've tried various packages such as require-all and import-all but both do not provide a solution to simply import all the files inside of the folder. I've also manually tried reading each file and importing them through a loop as well.

**Describe the solution you'd like**
 A configuration tweak that would allow us to just import all by specifying a folder path would be really nice.

**Describe alternatives you've considered**
Described in Description.

**Additional context**
Maybe even... something like: for index.js
```
alt.importAll('folderPathHere');
```

**Comment by emcifuntik** [comment]
Do you need it to import data from all scripts, or just to run all scripts from folder?

**Comment by FabianTerhorst** [comment]
Nodejs already supports dynamic imports, you just need to recursively add all files
```js
import('./test.mjs')
.then(t => {
  t.default();
})
.catch(err => {
  console.error(err);
});
```

**Comment by Stuyk** [comment]
> Nodejs already supports dynamic imports, you just need to recursively add all files
> 
> ```js
> import('./test.mjs')
> .then(t => {
>   t.default();
> })
> .catch(err => {
>   console.error(err);
> });
> ```

Here's a botched solution to this for now. It works for your idea. Thanks.
```
import fs from 'fs';
import path from 'path';

const modulePath = './resources/myresource';

function walk(currentDirPath, callback) {
    fs.readdir(currentDirPath, function (err, files) {
        if (err) {
            throw new Error(err);
        }
        files.forEach(function (name) {
            var filePath = path.join(currentDirPath, name);
            var stat = fs.statSync(filePath);
            if (stat.isFile() && filePath.includes('.mjs') && !filePath.includes('index.mjs')) {
                var firstPath = filePath.replace(`resources\\myresource\\server\\`, `.\\`);
                var finalPath = firstPath.replace(/\\/g, `/`);
                console.log(finalPath);
                callback(finalPath, stat);
            } else if (stat.isDirectory() && !filePath.includes('client')) {
                walk(filePath, callback);
            }
        });
    });
}

walk(modulePath, (file, stat) => {
    try {
        import(file);
    } catch(err) {
        console.log(err);
    }
});
```

**Comment by Stuyk** [comment]
Here's a full demonstration of it that has better code:
https://github.com/Stuyk/AltV-JS-Boilerplate/blob/master/resources/myresource/server/startup.mjs
