### ISSUE TITLE
[Bug] Move text "alt:V Multiplayer has started" to another position

### ISSUE THREAD

**Issue by dayvoo** [altmp/altv#132]
The info text "alt:V Multiplayer has started" in the upper left corner overlaps the GTA 5 native help texts. See the screenshot below.

## Possible Solutions
- Make the text way more transparent
- Move the text to another position
- Completely remove the text if it is not necessary

## Screenshot
https://i.imgur.com/WBlKOEP.png

**Comment by tastydev** [comment]
I think the chat resource holds this string if so just delete it.

**Comment by 7Hazard** [comment]
This is not something that exists by default on alt:V. Most probably one of your resources.
