### ISSUE TITLE
[Bug] GTA V is not completely closed

### ISSUE THREAD

**Issue by timedotcc** [altmp/altv#133]
## Expected Behavior
Close GTA

## Current Behavior
If you want to restart alt:V, Steam always complains that GTA is still running. So you have to quit Steam first and then start alt:V.

## Steps to Reproduce

1. Start alt:V
2. Quit alt:V
3. Start alt:V -> Steam error

**Comment by KifKick** [comment]
I don't have this problem. I have steam version too.

**Comment by timedotcc** [comment]
> I don't have this problem. I have steam version too.

Beta or stable branch?

**Comment by vadzz-dev** [comment]
Related to #170
