### ISSUE TITLE
[Bug] Persistent Local Cameras and Blips

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv#137]
## Expected Behavior
Create a camera locally. Interpolate; do whatever. Disconnect from the server. Camera views are deleted upon reconnect/disconnect.

Create a blip locally. Reconnect. Blips are re-parsed and created by server.

## Current Behavior
Create a camera locally. Disconnect from the server. Current camera still exists.

Create a blip locally. Reconnect. Blips are still there.

## Possible Solution
local disconnect event to handle it ourselves; or auto-delete cameras and blips on disconnect / reconnect.

## Steps to Reproduce
1. Create Camera or Blip
2. Reconnect
3. ???
4. Profit

## Context (Environment)
Its just a minor annoyance.

## Detailed Description
Simply delete any existing cameras or blips on disconnect. Then reconnect will have fresh instances of cameras.

**Comment by 7Hazard** [comment]
Currently everything created via natives will leave the script resources.

**Comment by FabianTerhorst** [comment]
doesn't disconnect event exists in client?
```js
alt.on("disconnect", () => {
            if (this.characterCreatePed !== 0) {
                game.deleteEntity(this.characterCreatePed);
            }
});
```

**Comment by MacieGx** [comment]
> doesn't disconnect event exists in client?
> 
> ```js
> alt.on("disconnect", () => {
>             if (this.characterCreatePed !== 0) {
>                 game.deleteEntity(this.characterCreatePed);
>             }
> });
> ```

Yea it's exists and working well.

**Comment by Stuyk** [comment]
> > doesn't disconnect event exists in client?
> > ```js
> > alt.on("disconnect", () => {
> >             if (this.characterCreatePed !== 0) {
> >                 game.deleteEntity(this.characterCreatePed);
> >             }
> > });
> > ```
> 
> Yea it's exists and working well. It's called before resource unload.

Had no idea we had disconnect on client-side. Okay then.
