### ISSUE TITLE
[Bug] Clientside console spam of SetPosition and SetEntityPosition

### ISSUE THREAD

**Issue by sirbenson** [altmp/altv#142]
Branch: Beta
Serverside language: C#
C# module version: 1.74-beta
AltV .NET Core Server Api 1.7.4-beta

## Current Behavior
After player spawn the clientside console is spamming SetEntityPosition and SetPosition true

## Steps to Reproduce
1. Spawn serverside player
[clientlog.log](https://github.com/altmp/altv/files/3269613/clientlog.log)

**Comment by Hardy535** [comment]
Can be closed, was related to this: https://github.com/altmp/altv/issues/154
