### ISSUE TITLE
[Bug] Request interiors failed

### ISSUE THREAD

**Issue by sirbenson** [altmp/altv#144]
Branch: Beta
Serverside language: C#
C# module version: 1.74-beta
AltV .NET Core Server Api 1.7.4-beta

## Expected Behavior
Request or remove any interiors

## Current Behavior
Requesting or removing any interiors with alt.requestIpl() or alt.removeIpl() clientside doenst work
No errors or informations in clientside console

## Steps to Reproduce
1. Create clientside command with request and remove ipl and type in any ipls

**Comment by sriem** [comment]
are you reloading ? after request ?

**Comment by sirbenson** [comment]
Working in master branch. You dont need du reload after interior request

**Comment by Hardy535** [comment]
Fixed, was related to this: https://github.com/altmp/altv/issues/154
