### ISSUE TITLE
Show overall download progress

### ISSUE THREAD

**Issue by datWeazel** [altmp/altv#147]
**Is your feature request related to a problem? Please describe.**
Just connected to a server that isn't mine and I didn't know how many files/mods are going to be downloaded. At every mod I was like "oh, that must be the last" and then another one downloaded. Would be nice to see per file/mod AND overall download progress while connecting not just the per file/mod progress that's currently shown.

**Comment by FabianTerhorst** [comment]
Its downloading one file / resource. So you could show the resources that needs to download.

**Comment by FabianTerhorst** [comment]
New ui in beta shows full download size.
