### ISSUE TITLE
[Bug] GetSyncedMetaData

### ISSUE THREAD

**Issue by mariusz5581** [altmp/altv#149]
## Expected Behavior

GetSyncedMetaData should get the same value which is set when using  SetSyncedMetaData
## Current Behavior

GetSyncedMetaData gives always 0 (zero)
## Steps to Reproduce

public static void OnConnect(IPlayer tPlayer)
        {
            Players t = new Players();
            for(int i = 0; i < all.Length; i++)
            {
                if(all[i] == null)
                {
                    t.qID = i;
                    t.player = tPlayer;
                    tPlayer.SetSyncedMetaData("qID", t.qID);
                    tPlayer.SetData("qIDL", t.qID);
                    all[i] = t;
                    break;
                }
            }
            Alt.Log(tPlayer.Name + " connecting qID:" + t.qID);
            

        }

        public static void OnDisconnect(IPlayer tPlayer)
        {
            int tID = -1;
            tPlayer.GetSyncedMetaData("qID", out tID);
            //tPlayer.GetData("qIDL", out tID);
            Alt.Log(tPlayer.Name + " disconnecting all[tID].qID:" + all[tID].qID + " for qID:" + tID);
            all[tID] = null;
        }
## Context (Environment)

So I have tested GetData and SetData just to compare and it is working. Haven't tested cross client-server. Only server-server, but in my opinion it should behave same like SetData and GetData when used only on server side

**Comment by FabianTerhorst** [comment]
meta data's only support ulong, long, double ect. not int, uint float ect.

**Comment by FabianTerhorst** [comment]
@vadzz-dev can be closed
