### ISSUE TITLE
Add event onMetaChange (both)

### ISSUE THREAD

**Issue by KifKick** [altmp/altv#15]
`alt.on('onMetaChange', (entity, key, value) => {
})`

**Comment by emcifuntik** [comment]
Use cases?

**Comment by FabianTerhorst** [comment]
When you have a synced meta data on your player like the position of a attachment and change that synced meta data, the native call needs to be recalled with the updated values.

**Comment by emcifuntik** [comment]
It can be usefull only for syncedMeta. I don't see use cases for one-side meta

**Comment by FabianTerhorst** [comment]
yeah i thought he mean synced meta data, maybe rename the issue?

**Comment by FabianTerhorst** [comment]
and the event is only needed on client side for entities that are in streaming range.
