### ISSUE TITLE
[Bug] setPedHeadBlendData will reset on repositioning

### ISSUE THREAD

**Issue by GangstaSunny** [altmp/altv#150]
If you set the pedData (like dad shape, mother shape etc.) and you set the Position of a player, the comps will be resetted.

## Expected Behavior
no reset

## Current Behavior
reset

## Steps to Reproduce
use game.setPedHeadBlendData and reposition the player.

**Comment by FabianTerhorst** [comment]
How you set the position. With natives or server side?

**Comment by GangstaSunny** [comment]
Serverside (using C#). I remember that u told me the player is being spawned when setting the position (which may also is the reason why he gains 100hp again)

**Comment by vadzz-dev** [comment]
Should be fixed in beta branch

**Comment by emcifuntik** [comment]
Not reproducable
