### ISSUE TITLE
[Bug] Player teleports under map on emitLocked

### ISSUE THREAD

**Issue by sirbenson** [altmp/altv#154]
Branch: Beta
Serverside language: C#
C# module version: 1.75-beta
AltV .NET Core Server Api 1.7.5-beta

## Expected Behavior
-

## Current Behavior
Player is teleporting under the map.

## Steps to Reproduce
Just send a player.EmitLocked Event. After emit the player will be teleported under the map
Tested with an clean beta server based on c#

**Comment by Hardy535** [comment]
Fixed, was an issue in the C# module.
