### ISSUE TITLE
[Bug] Fix clouds jumping if alt.setMsPerGameMinute() is set to e.g. 60000

### ISSUE THREAD

**Issue by derRAV3N** [altmp/altv#155]
We did set alt.setMsPerGameMinute() to 60000 so a GTA day is a real life day. Now the clouds are jumping every second.

## Expected Behavior

The game's day has a duration of 24 real life hours and clouds transitioning and moving should be as smooth as the normal timing or even smoother since its a **longer** duration than the default gta day

## Current Behavior

Clouds are jumping position and changing their look every second.

## Possible Solution

I think alt.setMsPerGameMinute() just sets the ingame duration every second, while it eventually should be set more often to prevent the clouds from jumping. But I don't know how this does affect performance.

## Steps to Reproduce

Videoproof: https://youtu.be/rv1yJIBQRpY
1. set alt.setMsPerGameMinute(60000)
2. wait for a time of day when there are actually clounds transitioning, sometimes it's just clear.

## Context (Environment)

I just want to make the world have real time and clounds transitioning smoothly.

## Detailed Description

--

## Possible Implementation

See [Possible Solution](#-possible-solution)

**Comment by emcifuntik** [comment]
I can't reproduce. Need time, weather and all data to see the same.

**Comment by derRAV3N** [comment]
I'm pretty sure now that there is not an easy way to fix this issue, since clouds are time-based and the default timing is 30x faster (default ingame day lasts 48 minutes, this makes it last 24h), and it makes sense that clouds are jumping now (30x faster could be already quite fluent).

Weather is extrasunny, time is for example 1st January 2019, 7AM.
You need to look up directly in the air to look at clouds that are "near" you. Clouds in the distance don't move that much for it being visible.
Position could be e.g. -852.20 -2141.62 101.38.

Hmm, I now wrote this post and afterwards checked again by setting weather and time, but  the clouds are different and can also be not visible. Also I noticed that there are two types of clouds. 1st are those of the skybox, 2nd are those which you're able to see when you e.g. switch characters in singleplayer which just  float above the map in one layer. those last are transitioning smoothly, the ones in the skybox are jumping.

**Comment by emcifuntik** [comment]
Try to play with "setWindSpeed" native

**Comment by derRAV3N** [comment]
I used that already in the past and tested it for this issue now, it doesn't change the behaviour of those clouds. Only trees and bushes are moving a bit faster, leaves and fog is moving faster, wind sound is heavier.

**Comment by vadzz-dev** [comment]
Can not reproduce too
