### ISSUE TITLE
[Bug] Reconnecting causes wrong ids to appear in some events.

### ISSUE THREAD

**Issue by Kudze** [altmp/altv#159]
Was working on my streamer, when I noticed, that reconnecting to a server via console caused crashes. While investigating I found, that playerID recieved from playerConnect and playerDisconnect wasn't the same as in alt.Player.all array.

## Expected Behavior

ID should be the same.

## Current Behavior

This code:

```
alt.on('playerConnect', (player) => {
  console.log(`PlayerConnect:  ${player.id}`);
});

alt.on('playerDisconnect', (player) => {
  console.log(`PlayerDisconnect:  ${player.id}`);
});

setInterval(
  () => {
    let usedIDs = [];
    
    for(let i = 0; i < 5; i++)
      if(alt.Player.all[i] !== undefined) usedIDs.push(i);

    if(usedIDs.length !== 0)
      console.log(usedIDs);
  },
  5000
);
```

Produces those results: 
```
PlayerConnect:  0
[ 0 ]
[ 0 ]
PlayerDisconnect:  0
PlayerConnect:  1
[ 0 ]
[ 0 ]
PlayerDisconnect:  1
PlayerConnect:  2
[ 0 ]
[ 0 ]
[ 0 ]
[ 0 ]
[ 0 ]
PlayerDisconnect:  2
```

I was the only player on a server. Connected to a server, walked around a bit. Then reconnected. Waited. Reconnected again. And left.

## Steps to Reproduce

1.
1.
1.
1.

## Context (Environment)

Server-Side

**Comment by FabianTerhorst** [comment]
The entity id is not reused always again it will reuse it when max is reached. Its not a bug that by design.
