### ISSUE TITLE
[Bug] Creating ~100 Blips causes crash on disconnect

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#160]
When creating around 100 blips via `alt.PointBlip` the client will crash on disconnect since beta release **#582**, before this never happened.
When creating 50 blips it will crash on the second disconnect and not on the first one (so after a total of 100 blips is created), so maybe something internally is not removed correctly?

_Side note:_ The blips are getting correctly removed from the ingame map.

## Steps to Reproduce
`for (var i = 0; i < 100; i++) {
new alt.PointBlip(0, 0, 0);
}`

**Comment by emcifuntik** [comment]
Fixed in Build 595
