### ISSUE TITLE
[Bug] Vehicle number plate bug

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#163]
There's a number plate streaming bug: I create 2 vehicles wich has totally different numberplate text (server-side). However when I join to the server and I check there , one of the vehicles get the other one's number text. (Text and type as well)

When I create a server side log of the numberplate's text it shows the correct value.

**Comment by derRAV3N** [comment]
You should probably post some code since this sounds very much like not a bug on alt:V's end.

**Comment by emcifuntik** [comment]
![image](https://user-images.githubusercontent.com/4309694/60117824-95b9c300-9783-11e9-9bdd-870afc7553d9.png)
Not reproduced

**Comment by Lekenthun** [comment]
Because the bug happens 1 time out of 10. Here are 2 pictures to demonstrate it:
https://i.imgur.com/qYIYOQs.jpg
https://media.discordapp.net/attachments/511285543250952202/591671970178007050/unknown.png?width=832&height=468

When I get the plate number with numberPlateText from server sie, then it give the real value. However as You can see in the picture the value isn't correct. Please check the Zentorno in the picture. It should have "Legend" text on it. And the numberplate style isn't the basic one as it should have been.

**Comment by FabianTerhorst** [comment]
Are you setting number plates via natives?

**Comment by Lekenthun** [comment]
No. I using numberPlateText property in server-side.

**Comment by Lekenthun** [comment]
My script: https://i.imgur.com/zUVLxmU.png

**Comment by Lekenthun** [comment]
This is what I figured out: it seems like the vehicle desyncronises when the problem with the number plates happens as I can't set the number plates' text , nothing happens. You can see this on the pictures.
https://i.imgur.com/zDJxHrx.jpg

**Comment by emcifuntik** [comment]
Finally reproduced. Fixing

**Comment by emcifuntik** [comment]
Fixed
