### ISSUE TITLE
[Bug] checkpoint.dimension server crash

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#164]
I think the changing dimension in chekpoint makes the server crash. Without changing dimension it works, with it crashes (Actually it closes without log)

Example:
var cp = new alt.Checkpoint(45, 0,0,70, 3, 3, 0, 131, 255, 190);
cp.dimension = 1;

**Comment by FabianTerhorst** [comment]
How does the console log looks like after the crash?

**Comment by Lekenthun** [comment]
Only closes. No logging.

**Comment by FabianTerhorst** [comment]
Start it with powershell.

**Comment by Lekenthun** [comment]
No mistakes. It just closes.

**Comment by FabianTerhorst** [comment]
When you start it with e.g. powershell or a bash script that pauses the console after close it will keep showing the log.

**Comment by Lekenthun** [comment]
I know. But server is no logging.

**Comment by Lekenthun** [comment]
https://i.imgur.com/advz7It.png

**Comment by FabianTerhorst** [comment]
ah ok.
