### ISSUE TITLE
Add getMod and getExtra for Vehicle API

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#165]
It would be good the getMod and getExtra function in server-side.

Example:
vehicle.getMod(category)
vehicle.getExtra(category)

**Comment by FabianTerhorst** [comment]
The methods are missing in node module, because cpp sdk already provides a api for getting the mod and the vehicle extras.

**Comment by Lekenthun** [comment]
Who can I write to to make the functions added to the node module?

**Comment by emcifuntik** [comment]
Added
