### ISSUE TITLE
[Bug] Vehicle Siren of Modded Cars work after Reconnect

### ISSUE THREAD

**Issue by cwoomi** [altmp/altv#166]
## Expected Behavior
The siren should work on first connection

## Current Behavior
currently vehicle sirens of modded cars start working after using "reconnect" in the console - beforehand it doesn't work at all

**Comment by DasChaosAT** [comment]
related/duplicate to #31

**Comment by emcifuntik** [comment]
> related/duplicate to #31

It's solution for related issue

**Comment by vadzz-dev** [comment]
Discussion moved to #31
