### ISSUE TITLE
Return the struct provided by game.getPedHeadBlendData

### ISSUE THREAD

**Issue by indilo53** [altmp/altv#167]
**Is your feature request related to a problem? Please describe.**
Actually game.getPedHeadBlendData returns something like [true, 0] in javascript so we can't fetch the head blend data from the ped and we have to rely on custom stuff to get it working.

**Describe the solution you'd like**
Return the struct as an object / array

**Describe alternatives you've considered**
Implement it directly in alt.Player

**Comment by DasChaosAT** [comment]
**Additional Infos dev-c.com/nativedb/ :**

BOOL _GET_PED_HEAD_BLEND_DATA(Ped ped, Any *headBlendData)
// 0x2746BD9D88C5C5D0

The pointer is to a padded struct that matches the arguments to SET_PED_HEAD_BLEND_DATA(...). There are 4 bytes of padding after each field.

(Edit) Console Hash: 0x44E1680C

pass this struct in the second parameter
```
typedef struct
{
int shapeFirst, shapeSecond, shapeThird;
int skinFirst, skinSecond, skinThird;
float shapeMix, skinMix, thirdMix;
} headBlendData; 
```

**Comment by FabianTerhorst** [comment]
Reminder for vadzz:
"VadZz: I will make it to use js buffers for custom structs
you will just provide a buffer as arg and it will write to it"

**Comment by indilo53** [comment]
Fixed in build 748 with the usage of MemoryBuffer
