### ISSUE TITLE
[Bug] All .emit functions strip numeric keys, resursively

### ISSUE THREAD

**Issue by rsxdalv** [altmp/altv#168]
## Expected Behavior

Objects get transferred according to JSON spec.

## Current Behavior

`{x: { x: 3, "9": 4, z: 3}}` -> `{x: { x: 3, z: 3}}`
`{ x: 3, "9": 4, z: 3}` becomes `{ "x": 3, "z": 3}`
while https://jsonlint.com/ marks `{"9":4,"x":3,"z":3}` as valid

## Steps to Reproduce

1.
1.
1.
1.

**Comment by vadzz-dev** [comment]
should be fixed in build 637, needs confirmation
