### ISSUE TITLE
[Bug] Entering collision shapes crashes the server

### ISSUE THREAD

**Issue by rsxdalv** [altmp/altv#174]
When a player enters a colshape, the server crashes

## Steps to Reproduce

1. Create colshape
1. Enter it
1. Server crash
1. gdb output: `0x00007ffffd017ca9 in V8Resource::GetOrCreateEntity(alt::IBaseObject*, char const*) [clone .isra.312] () from modules/libnode-module.so`

**Comment by Matspyder51** [comment]
What build do you use ?

**Comment by rsxdalv** [comment]
Appears fixed, though I did have a lagspike when entering first colshape, possibly due to client code.
