### ISSUE TITLE
[Bug] Native checkpoints remain after reconnect

### ISSUE THREAD

**Issue by rsxdalv** [altmp/altv#176]
Creating checkpoints that fail to be deleted will make them stay after reconnecting.

## Steps to Reproduce

1.
1.
1.
1.

**Comment by FabianTerhorst** [comment]
Suggestion would probably be to provide a api on clientside to create checkpoints, like for blips.
```
new alt.Checkpoint()
```

**Comment by rsxdalv** [comment]
Yes, but then I'd have to replace the original functions if they leave side effects after reconnect.

**Comment by vadzz-dev** [comment]
Moved to #193
