### ISSUE TITLE
[Bug] Exmpty javascript in html causes errors

### ISSUE THREAD

**Issue by TylkoKuba** [altmp/altv#177]
Empty javascript in html causes errors.

## Expected Behavior

If you would include empty javascript it should work completely normal.

## Current Behavior

If you would include empty javascript in html when joining the server the webView will throw an error 'Request failed with status 404'

**Comment by FabianTerhorst** [comment]
Can you add the code to reproduce?

**Comment by Stuyk** [comment]
Failed to add reproduction steps.
