### ISSUE TITLE
Add client js websocket support 

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv#18]
alt.WebSocket("...")

**Comment by gamelaster** [comment]
Usage?

**Comment by FabianTerhorst** [comment]
Connecting to a websocket server for exchanging informations without using a workaround via a webview.

**Comment by gamelaster** [comment]
But why lol? Why you need connecting to WebSocket when you can communicate with server via emit etc

**Comment by tastydev** [comment]
^this + if you need it just create a cef window

**Comment by emcifuntik** [comment]
Useless
