### ISSUE TITLE
[Suggestion] vehicle.model setter

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#186]
It would be great if you can change vehicle models on server side. (vehicle.model property)

**Comment by emcifuntik** [comment]
Not possible

**Comment by vadzz-dev** [comment]
GTA engine does not allow to change model on runtime

**Comment by Lekenthun** [comment]
Other multiplayer clients do have model change on server side. Do you know how does it work at their clients?

**Comment by rsxdalv** [comment]
If you perfectly recreate the vehicle that's equivalent. I can attest that model changes behave exactly as that.

**Comment by FabianTerhorst** [comment]
And i don't know any mod that is doing that, because you would also need to check for players inside ect.

**Comment by rsxdalv** [comment]
True, but all I'm saying is that under the hood changing models does the
same things as respawning a new car, an example of this is radio and engine
resetting. Bottom line is, I believe this can be polyfilled in JavaScript,
it's just not as convenient as it being ready.
