### ISSUE TITLE
[Bug] Connection bug

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#189]
One of my friends (Dani) try to connect to my server. He couldn't as he had an older build. He got the "Can't connect" message. The more important thing is that the server shows that he is connected. It doesn't even disconnects him even when we waited some time. I ran 1-1 script on client side and server side which lists the online players. On client side it showed him 2x, on server side showed him 3x. He tried to connect only 2 times.

Version: #632

Test script:
alt.Player.all.forEach((p) => { alt.log("player: " + p.name) })

_Results:_
**Server-side:**
[23:50:18] player: Dani
[23:50:18] player: Dani
[23:50:18] player: Lekent
[23:50:18] player: Dani
**Client-side:**
[23:50:01] player: Dani
[23:50:01] player: Dani
[23:50:01] player: Lekent

Picture:
https://i.imgur.com/5PT4LnK.png

**Comment by vadzz-dev** [comment]
Fixed in latest beta
