### ISSUE TITLE
[Bug] vehicle.pos

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#190]
When the vehicle is far away (out of stream distance range) and you want to change its position then the vehicle doesn't teleport there.

**Comment by FabianTerhorst** [comment]
So changing position without a near player doesn't work? Maybe thats the same reason why numberplate sometimes doesn't work.

**Comment by Lekenthun** [comment]
> So changing position without a near player doesn't work? Maybe thats the same reason why numberplate sometimes doesn't work.

Yes, possible.

**Comment by vadzz-dev** [comment]
Duplicate of #71
