### ISSUE TITLE
[Bug] [CEF] Console output shows without debug enabled

### ISSUE THREAD

**Issue by KifKick** [altmp/altv#196]
## Is your feature request related to a problem? Please describe.
CEF console output shows without enabled debug mode.

## Describe the solution you'd like
Disable console outputs from cef when debug is disabled.

**Comment by KifKick** [comment]
And same for other errors, from v8 etc

**Comment by FabianTerhorst** [comment]
debug mode is only for reconnect and chrome debugger not for console log.

**Comment by KifKick** [comment]
Yeah but some errors from cef etc I think should be only available in debug mode

**Comment by FabianTerhorst** [comment]
i don't think so. But let's wait for other opinions.

**Comment by vadzz-dev** [comment]
Why should it? It writes the to a file anyway
