### ISSUE TITLE
Allow "--experimental-worker" as startparam for nodejs

### ISSUE THREAD

**Issue by OskarSniper** [altmp/altv#200]
**Is your feature request related to a problem? Please describe.**
I'd like to use worker_threads in nodejs to do CPU intensive tasks with those workers. Right now it's only an experimental feature and needs to be enabled via "--experimental-worker".

**Describe the solution you'd like**
Add the possibility to start the internal node process with own arguments, maybe for future experimental builds.

**Describe alternatives you've considered**
Start the node process with --experimental-worker.

**Comment by adnanbrq** [comment]
I would suggest just upgrading Node from 10.6.0 to latest LTS

**Comment by ccrumbb** [comment]
It's nice to have but as workaround you still can use `Cluster` https://nodejs.org/docs/latest-v10.x/api/cluster.html for high CPU tasks.

**Comment by OskarSniper** [comment]
`Cluster` as workaround isnt quite efficient. The big difference in `Cluster` & `Worker Threads` is memory sharing.

"Unlike child_process or cluster, worker_threads can share memory. They do so by transferring ArrayBuffer instances or sharing SharedArrayBuffer instances."

[Worker Threads](https://nodejs.org/api/worker_threads.html#worker_threads_worker_threads)
[Cluster vs Worker Threads](https://stackoverflow.com/a/57227589/5802172)

**Comment by ccrumbb** [comment]
> `Cluster` as workaround isnt quite efficient. The big difference in `Cluster` & `Worker Threads` is memory sharing.
Yes, indeed. But still with some effort to serialize data you can easily delegate CPU intensive tasks to Cluster. I'm 100% agree that workers are better in this case but it's also possible via Cluster as workaround. For sure the best way and I guess the simple one would be allowing to use experimental flag with workers.

**Comment by vadzz-dev** [comment]
Node version got updated to 12.4.0

**Comment by ccrumbb** [comment]
Actually it still doesn't work. Worker threads module is accessible, but spawning of workers doesn't work.
During spawning worker:
```Error: The V8 platform used by this instance of Node does not support creating Workers
    at new Worker (internal/worker.js:105:21)
    at file:///mnt/e/Workplace/oesis-altv/build/linux/resources/oesis/server/index.js:7:16
    at ModuleJob.run (internal/modules/esm/module_job.js:111:37)
    at async Loader.import (internal/modules/esm/loader.js:131:24)
    at async _third_party_main.js:30:16 {
  code: 'ERR_MISSING_PLATFORM_FOR_WORKER'
}
```
According to NodeJS documentation (https://nodejs.org/api/errors.html#errors_err_missing_platform_for_worker):
```ERR_MISSING_PLATFORM_FOR_WORKER#
The V8 platform used by this instance of Node.js does not support creating Workers. This is caused by lack of embedder support for Workers. In particular, this error will not occur with standard builds of Node.js.```
