### ISSUE TITLE
[Bug] game.transitionToBlurred(1); doesn't reset on reconnect

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv#202]
## Expected Behavior
game shouldn't get blurred after reconnect.

## Current Behavior
Game stilled blurred.

## Possible Solution
Call game.transitionFromBlurred(1) manually.

## Steps to Reproduce
Call game.transitionToBlurred(1) somewhere in code.
Reconnect
Screen still blurred even when blur code isn't executed on start of client script.

## Context (Environment)
647 beta both server and client

**Comment by vadzz-dev** [comment]
Related to #193
