### ISSUE TITLE
[Bug] Spanish languaje lags the whole Alt-v interface

### ISSUE THREAD

**Issue by Radeoxx** [altmp/altv#211]
## Expected Behavior
Should run smoothly

## Current Behavior
The whole Alt-v interface is laggy.

## Steps to Reproduce
1. Just set the Alt-v client to spanish via settings in main menu.

**Comment by FabianTerhorst** [comment]
Its because console logs a lot of errors for missing translation keys.

**Comment by KubasGC** [comment]
Same bug for Polish language

**Comment by vadzz-dev** [comment]
Oh, i forgot to push fix :/

**Comment by vadzz-dev** [comment]
Should be fixed now
