### ISSUE TITLE
[Bug] Client crash upon spawning a custom vehicle resource.

### ISSUE THREAD

**Issue by AndreiiiH** [altmp/altv#213]
When trying to use a custom vehicle resource, the client crashes upon spawning said custom vehicle.
Furthermore, extended testing has shown that all clients within streaming distance of the vehicle being spawned are crashed. This has been tested with multiple vehicles, to no avail.

## Expected Behavior
The vehicle should be spawned.

## Current Behavior
Client crash on vehicle spawning.

## Possible Solution

N/A

## Steps to Reproduce

1. Download the attached ZIP file [executioner.zip](https://github.com/altmp/altv/files/3443168/executioner.zip)
1. Unarchive into the `resources` folder
1. Add the resource to `server.cfg`
1. Connect to the server
1. Spawn the vehicle

## Context (Environment)

Using alt:V #718 client, #712 server.

**EDIT (31/07/2019):** Modified to match the actual issue, as the original was solved by Lhoerion below.

**Comment by Lhoerion** [comment]
Client fails to load meta files as asset file, it's not a bug.
Meta files shouldn't be included in `stream.cfg` property `files`, only in `meta` property.
Example of folder hierarchy:
```
- stream
-- *.meta
-- assets
--- *.*
- resource.cfg
- stream.cfg
```

**Comment by AndreiiiH** [comment]
Having modified the `stream.cfg` file to the following:
```json
files: [
  stream/assets/*
]

meta: {
  stream/carvariations.meta: VEHICLE_VARIATION_FILE
  stream/vehicles.meta: VEHICLE_METADATA_FILE
  stream/dlctext.meta: TEXTFILE_METAFILE
  stream/handling.meta: HANDLING_FILE
}

gxt: {
  executioner: executioner
}
```

This removed the errors from the console, however, the client still crashes upon vehicle spawn, using the following code:
```js
export function spawnVehicle(player, arg) {
	if (!arg[0])
		return player.sendMessage('{FF0000}Vehicle type is not valid.');

	if (player.vehicle !== undefined) {
		try {
			player.vehicle.destroy();
		} catch (err) {
			player.vehicle = undefined;
		}
	}
		
	const positionNear = extended.RandomPosAround(player.pos, 10);

	try {
		var vehicle = new alt.Vehicle(arg[0], positionNear.x, positionNear.y, positionNear.z, 0, 0, 0);
		vehicle.dimension = player.dimension;
		setTimeout(() => {
			alt.emitClient(player, 'warpIntoVehicle', vehicle);
			player.showSubtitle('~g~You have spawned a vehicle.', 3000);
		}, 500);
	} catch(err) {
		player.sendMessage('{FF0000}Vehicle type is not valid.');
	}
}
```

No errors are thrown in either consoles or files, once again.

Updated resources:
[executioner.zip](https://github.com/altmp/altv/files/3443343/executioner.zip)
[taranis.zip](https://github.com/altmp/altv/files/3443345/taranis.zip)

**Comment by leNicDev** [comment]
Same issue here. The game crashes while joining the server. These are the last two log messages:
```
[15:40:57] Starting resource:  bmwm3s
[15:40:58] MiniDump created.
```

stream.cfg:
```
files: [
  stream/bmwm3s/*
]

meta: {
  stream/bmwm3s/vehicles.meta: VEHICLE_METADATA_FILE
  stream/bmwm3s/carvariations.meta: VEHICLE_VARIATION_FILE
  stream/bmwm3s/dlctext.meta: TEXTFILE_METAFILE
  stream/bmwm3s/handling.meta: HANDLING_FILE
}

gxt: {
  bmwm3s: bmwm3s
}
```

**Comment by grtiernan** [comment]
I'm pretty sure it is mod specific. I have a 7 vehicle police pack which all works fine, without any issues or crashes whatsoever. But when I try to add a fire department pack alongside it, the exact same way I did with the police ones it crashes.

Crazy thing is, if you try load these mods in singleplayer they all work without any issues or crashes. Could be related to the alt:V client not having a decent game config to work with these vehicles but I'm just half speculating at that point.

**Comment by AndreiiiH** [comment]
@grtiernan Could you please provide said police pack so we can test and see if we experience the same behaviour?

**Comment by leNicDev** [comment]
I discovered something. I was using this tool (https://forum.altv.mp/index.php?/topic/60-custom-vehicle-to-resource-tool) to generate resources from car mods from gta5-mods.com. It seems like it generates a malformed resource.cfg:

```
type: dlc,
main: stream.cfg,

client - files: [
  stream/*
]
```

When I changed the `client - files: [` to `client-files: [`, it the client connected without crashing.

**Comment by leNicDev** [comment]
Now I get the same behavior as @AndreiiiH

**Comment by Lhoerion** [comment]
I've checked again, `*.yft` & `*.ytd` files seems to be corrupted.
It works for valid fragment objects and texture dictionaries, issue can be closed.
