### ISSUE TITLE
Unsupported game version / Pattern not found

### ISSUE THREAD

**Issue by sanyisasha** [altmp/altv#215]
Hey.  
Just downloaded the game, and got this error after "Unsupported game version".   
![altverror](https://user-images.githubusercontent.com/12791093/62153105-2bf18380-b304-11e9-9643-667326a9ef23.png)
Interesting, but beta runs without problem. (Except only one russian only server had players... :D)  Windows 10, steam gta v. (not cracked)

**Comment by FabianTerhorst** [comment]
Set ``branch: 'beta'`` in ``altv.cfg``.

**Comment by FabianTerhorst** [comment]
When beta get merged in stable, stable will support it as well.

**Comment by sanyisasha** [comment]
@FabianTerhorst so there is no stable currently?

**Comment by sanyisasha** [comment]
Btw, now it's work, closing.
