### ISSUE TITLE
[Bug] fire extinguisher invisible icon

### ISSUE THREAD

**Issue by Q-nik** [altmp/altv#221]
## Expected Behavior
fire extinguisher don't have icon on tab.

## Steps to Reproduce

1. get fire extinguisher
2. press tab

![Szkic](https://user-images.githubusercontent.com/53701664/62424020-23fd5f00-b6c9-11e9-884d-0989f7496ce1.png)

**Comment by vadzz-dev** [comment]
That's not an altv bug, gta 5 doesn't have icon for it
