### ISSUE TITLE
[Bug] disconnect event doesn't get called on reconnect

### ISSUE THREAD

**Issue by aviadmini** [altmp/altv#227]
`disconnect` event doesn't get called on reconnect

## Expected Behavior
Event is called when using `reconnect` in console

## Current Behavior
Event is not called

## Context (Environment)
`alt:V Server, build #728, branch beta`
I'm doing some cleanup (deleting peds, objects etc) on disconnect and I have to restart game to get clean state again. Extremely inconvenient

**Comment by FabianTerhorst** [comment]
You need to give more context about your environment. E.g. which script runtime you are using ect.

**Comment by aviadmini** [comment]
Since it's clientside it's javascript

**Comment by FabianTerhorst** [comment]
Only the code to reproduce.

**Comment by aviadmini** [comment]
```js
import * as alt from "alt";
alt.on('disconnect', cleanup);
function cleanup() {
    alt.log("disconnect cleanup"); // not called on reconnect
}
```

**Comment by aviadmini** [comment]
Update: looks like it's called only on first reconnect, on further reconnects it's not called again

**Comment by aviadmini** [comment]
The issue was elsewhere
