### ISSUE TITLE
Add TAR(BZIP) compression for CDN

### ISSUE THREAD

**Issue by Matix8981** [altmp/altv#229]
I suggest add compression tar(bzip or gzip) for cache CDN example solution is in SRCDS FASTDL bzip compression for files.

Compression in two side:
Server Generate Cache -> Compress Cache CDN to tar.bz2(example) -> Client download cache compressed -> decompress cache

**Comment by vadzz-dev** [comment]
1) HTTP protocol support supports compression itself
2) Resources are encrypted so compression won't give you a lot
