### ISSUE TITLE
Fix game camera rotating when showing the cursor/focusing webview

### ISSUE THREAD

**Issue by derRAV3N** [altmp/altv#23]
Currently the game camera rotates according to the movement of the mouse when showing it.
(Also clicks are listened to by the game: https://youtu.be/LWo7erjy34s)

**Comment by derRAV3N** [comment]
Okay so I looked up how GTA itself does it when having an UI opened.

When opening the phone, you have right-, leftclick, mousewheel, escape, backspace, enter, arrow keys reserved for interaction with the phone.

When opening e.g. the M-menu(all sorts of random stuff like inventory, getting the car by mechanic, GPS, ...) You have all the keys mentioned above, plus you can interact via mouse.

It would be great if we could block this in the same way, even nicer it would be if we could just block per-key (and then additionally optional camera movement when moving the mouse since that's not a key?).

**Comment by gamelaster** [comment]
Yes, we know about this, it will be fixed soon, but thank you for making the issue :)

**Comment by emcifuntik** [comment]
It's already implemented but not documented. use 
`alt.setCamFrozen(frozen: boolean): void;`

**Comment by derRAV3N** [comment]
> It's already implemented but not documented. use
> `alt.setCamFrozen(frozen: boolean): void;`

I just tested this, `alt.setCamFrozen(frozen: boolean): void;` detaches the camera from the player character, I want it to stay attached to the player but the mouse not be able anymore to move the camera.

**Comment by 7Hazard** [comment]
You have to disable the specific controls, you can do this via natives
