### ISSUE TITLE
[Bug] Some natives do not work without alt.nextTick

### ISSUE THREAD

**Issue by vadzz-dev** [altmp/altv#231]
- [x] requestScaleformMovie
- [x] setEntityInvincible

**Comment by FabianTerhorst** [comment]
- [ ] game.setEntityInvincible

**Comment by MacieGx** [comment]
_Sometimes_

[ ] removeBlip
[ ] deleteCheckpoint

**Comment by vadzz-dev** [comment]
Sone notification natives

**Comment by MacieGx** [comment]
- [] createCheckpoint

**Comment by emcifuntik** [comment]
Fixed
