### ISSUE TITLE
Made web rtc support and possibility to made https webview

### ISSUE THREAD

**Issue by bozoweed** [altmp/altv#232]
okey so because webview is using only http we can't use navigator.mediaDevices.getUserMedia()
to use Web RTC to make radio or phone

**Describe the solution you'd like**
the possibility to have webviw in https

**Describe alternatives you've considered**
as you want but i need rtc

**Comment by 7Hazard** [comment]
WebRTC will most probably not be available through webviews.
HTTPS support will be looked into in another issue.
Feel free to suggest things for the current voice system (alt-voice) or our API's to imrove and implement a sound API.
