### ISSUE TITLE
[Bug] createObject is not synced

### ISSUE THREAD

**Issue by jesst3r** [altmp/altv#233]
When spawning an object (using createObject) it spawns only locally, and not synced to the another players around.

## Expected Behavior
When calling createObject, it spawns and syncs properly to the all players around.

## Current Behavior
createObject spawns only locally

## Possible Solution
sync object created with createObject method over network.

## Steps to Reproduce
code snippet:
```
let localPlayer = alt.Player.local;
    let pos = localPlayer.pos;

    game.createObject(game.getHashKey("prop_mp_cone_01"), pos.x, pos.y, pos.z, true, false, true);
```

## Context (Environment)
using client and server build #735

**Comment by 7Hazard** [comment]
Generally things created and spawned from clientside code will not be synchronized.

Objects are not synchronized by default in GTAV however future serverside dynamic object sync is a future goal. That can be held in another issue.
