### ISSUE TITLE
[Bug] custom_ui_menumap  [Stream-resource]

### ISSUE THREAD

**Issue by Techlef** [altmp/altv#236]
**<! --- Provide a general summary of the issue in the title above ->**

A stream-resource was created. To replace the original menu map [ESC], it works only when you zoom out completely. If you zoom in, the new map disappears, and the original one is displayed.

It works without problem in the singleplayer, in the mods folder.

**ZoomOut:** https://media.discordapp.net/attachments/448489549065093130/610909088951435274/unknown.png?width=812&height=457 

**ZoomIn:** https://cdn.discordapp.com/attachments/448489549065093130/610910900718665768/unknown.png

**## Steps to Reproduce
<! --- Provide a link to a live example, or an unambiguous set of steps to ->**

**Download-link for resource** = http://tiny.cc/ntr5az

**Comment by lameule123** [comment]
The real problem is about mapzoomdata.meta currently not working as expected.
META file is not applied so ZoomOut/ZoomIn don't work correctly.

**Comment by FabianTerhorst** [comment]
Check again if its still not supported.
https://discordapp.com/channels/371265202378899476/585862696281571341/646380101835030579

**Comment by Lhoerion** [comment]
I can confirm, but that's not a bug, just minimap requires replacing other files. (which isn't supported last time I checked)

**Comment by lameule123** [comment]
Custom Map is working great with utilisation of custom map zoom API.

**Comment by Lhoerion** [comment]
Checked it again after @lameule123 comment, minimap appears to be a separate issue.
Thanks for the clarification @lameule123
