### ISSUE TITLE
[Bug] mod-vehicle not working anymore after #737 Update

### ISSUE THREAD

**Issue by Techlef** [altmp/altv#237]
****
**mod-vehicle has stopped working since last update # 737. The same happened sooner after the casino update with other mod vehicles.**

## Current Behavior

**Server starts normally and runs, but if this vehicle is in the resource, the client crashes when connecting the server.**

## Possible Solution

**maybe has something to do with the game config in GTA (Gameconfig.xml)? or there are changes happened in alt:v for the creation of the DLC?**

## Steps to Reproduce

**1.Resource in the server add.
2. Start the server.
3. connect to the server.
4. Download resources.
5. The client should crash now**

## Context (Environment)

**Add mod vehicles to server resource as a stream resource**

## Detailed Description

This happened earlier, I give a link in the describe with 32 other mod vehicles where also no longer work.

(isn`t working anymore since right after the #737 Alt:V update)
[streiter2.zip](https://github.com/altmp/altv/files/3499095/streiter2.zip)

[Pack with 32 ModVehicles](isn`t working anymore since right after Casino Update on Alt:V
https://drive.google.com/file/d/1X9Mhz0g5yPkmRMGPMD1KpgiwV3xEZGPk/view

**Comment by vadzz-dev** [comment]
can you pack whole resource with configs cause when i pack it manually streiter2 works fine

**Comment by Techlef** [comment]
Sure, here is the complete resource. which is strange, if the streiter2 and the 2015wbpolstang is in the rescource I get a client crash when i connecting. but is only 1 of both in the rescource, it works it again. It seems strange. 
[https://drive.google.com/file/d/1uhlvNlLXeh-pDKgM3ns8OmfG1Fu_iVQl/view?usp=sharing](Rescorce Download)

**Comment by Techlef** [comment]
So, here is a other resource(Like the other one),  with ja new other Car add to the resource the "unmarkedScout", same problem the client is crashing if client beginning to download the rescource...., i dont now it seems like its a limit of Cars...

https://drive.google.com/file/d/12ya19YGlZtOUX2o_1yOgLpTOELAcZu4h/view?usp=sharing

**Comment by Techlef** [comment]
I do not do it to annoy you, but I have another rescource here, where I added the CoastGuardpack. Same problem the client crashed. it's weird it looks as if the client does not like more than 10 vehicles. at the 11th vehicle what you add crashes the client.

I hope it helps you that I send you various resouces with different vehicles

download link
https://drive.google.com/file/d/1g-eQp0tQI1PTkvlAU-YpHUkw8aypAHff/view?usp=sharing

**Comment by FabianTerhorst** [comment]
You tried latest update 745?

**Comment by Lhoerion** [comment]
It's issue creator problem, not of alt:V.
Missing slashes in property `files` elements, wrong wildcards also.
Non existing files in property `meta` keys, unecessary dlctext.meta, both of these issues seems to be the essence of the problem.
After fixing problems mentioned above, everything works without crashes.
Issue can be closed, but in future please check everything in many different ways before posting an issue.

**Comment by Lhoerion** [comment]
Checked it today and it's fixed with #746 update

But your resources need config fixes like:
- missing slashes in property `files` elements, wrong wildcards also
- non existing files in property `meta` keys, unecessary `dlctext.meta`
