### ISSUE TITLE
[Bug] Sometimes vehicle.engineOn is bugged

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv#239]
## Expected Behavior
it's working asf

## Current Behavior
its bugged

## Possible Solution
Idk but its temp solution with working great (switching vehicle off)
```js
 vehicle.engineOn = true;
setTimeout(() => {
    vehicle.engineOn = false;
}, 100)
```
but sometimes you still have to turn the engine off and on twice for it to work.
## Detailed Description
Okay. So i'm checking vehicle.engineOn and when it's true i'm switching it to false.
Sometimes there is a problem that the engine does not turn off and after re-checking the vehicle.engineOn is still true.

What can affect this? I do not know. But I prevent the engine from switching off (I change its status) after leaving the vehicle by the client side.

**Comment by MacieGx** [comment]
sorry that was mb

**Comment by hacklover** [comment]
I got this problem too, with bmx. When testing alone everything is good but when another player joins, bmx can't move and I had to set engineOn true
