### ISSUE TITLE
Add possibility to get console visibility 

### ISSUE THREAD

**Issue by SokratesMir** [altmp/altv#241]
It would be a nice to have if you would be able to get the current status of the F8 console - is it opened or closed.

Wanting to block certain keyup/down triggers when console is open, but cannot find any solutions other then getting the current console visiblity (since reconnecting doesnt close/hide the console, a workaround is not easily possible).

Thanks

**Comment by ThomasMarangoni** [comment]
IsConsoleOpen was added to Beta Branch, can be closed

**Comment by Lhoerion** [comment]
https://altmp.github.io/altv-typings/modules/_alt_client_.html#isconsoleopen
https://altmp.github.io/altv-typings/modules/_alt_client_.html#ismenuopen
