### ISSUE TITLE
[Bug] Undefined Parameters on Vehicle Base64 Functions

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv#244]
Basically; use undefined on a Base64 function for a vehicle. Completely breaks it.

## Expected Behavior
Default to whatever value; or just have the server say bad base64 or something.

## Current Behavior
Assign undefined. Can't enter, exit, etc.

## Steps to Reproduce
```
let veh = alt.Vehicle('thrax', 0, 0, 0, 0, 0, 0);
veh.setHealthDataBase64(undefined);
```

## Context (Environment)
Accidentally assigned undefined and found out it just broke it.

**Comment by FabianTerhorst** [comment]
You should only assign values to the base64 setters you also get from them. That also means the values from them shouldn't be manipulated and the getter will never return undefined.

**Comment by vadzz-dev** [comment]
Yeah, that's how it works, xd. You basically reset health data when you don't know what it is. So yeah, herons answer is right: do not set anything except you get from appropriate getter

**Comment by 7Hazard** [comment]
@vadzz-dev this should be handled, invalid values should throw exceptions to not hide bugs

**Comment by FabianTerhorst** [comment]
Base64 methods are deprecated.

**Comment by FabianTerhorst** [comment]
the next version prevent usage of invalid base64 data.
