### ISSUE TITLE
Respawn after drowning isnt working

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv#25]

**Comment by vadzz-dev** [comment]
Do you mean that death event is not triggered or it is triggered, but player don't get respawned?

**Comment by FabianTerhorst** [comment]
We had multiple times that the player didn't respawn on freeroam server after drowning.

**Comment by FabianTerhorst** [comment]
So the event is probably not getting fired.

**Comment by derRAV3N** [comment]
I think you mean after dying?
Drowning is probably the wrong translation.

**Comment by FabianTerhorst** [comment]
No i mean drowning, in other situations it works.
