### ISSUE TITLE
[Bug] map store reloads with no map resource present

### ISSUE THREAD

**Issue by yoranjj** [altmp/altv#251]
If the server does not have a map resource present and a player connects/reconnects to it, the map store will reload anyway.

## Expected Behavior
Do not reload the map store if no map resource is present.

**Comment by Lhoerion** [comment]
What about a situation when you reconnect to the same server and before reconnect he had a map resource?

**Comment by yoranjj** [comment]
Doesn't seem to be an issue anymore, forgot this was open.
