### ISSUE TITLE
[Bug] isLoadingPromptBeingDisplayed returns string not boolean in natives.d.ts

### ISSUE THREAD

**Issue by aviadmini** [altmp/altv#253]
## Expected Behavior
`isLoadingPromptBeingDisplayed` is supposed to return boolean as per nativedb

## Current Behavior
`isLoadingPromptBeingDisplayed` returns a string

## Steps to Reproduce
Check natives.d.ts

**Comment by Lhoerion** [comment]
It's fixed after significant changes in natives, also worth mentioning is that
`Native isLoadingPromptBeingDisplayed renamed to busyspinnerIsOn`
