### ISSUE TITLE
[Bug] OnPlayerDamage Health is not/wrong calculated

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv#254]
## Expected Behavior
OnPlayerDamage OldHealth parameter should giving you the OldHealth between 0 and 100.

## Current Behavior
OldHealth parameter is giving back value between 100 and 200.

## Possible Solution
uint RealHealth = OldHealth - 100;

## Steps to Reproduce

1. Use the Event OnPlayerDamage.
2. Get hurt.

## Detailed Description
Giving back an corrected value for the OldHealth param.
Also there is a problem with the Damage value, already described in #51

**Comment by Stuyk** [comment]
```js
alt.on('playerDamage', (victim, attacker, damage, weapon) => {
	const actualDamage = 65536 - damage;
        victim.health += actualDamage;
});
```

If you're wondering; you can do this to get the real damage; and add it back to the user who was injured. This is a solution I've used in the past.

**Comment by FabianTerhorst** [comment]
Is the bug still present in latest version?

**Comment by Revyn112** [comment]
Yes this bug is still present on 1007.

![image](https://user-images.githubusercontent.com/7781906/74416841-ff3b2e80-4e45-11ea-8482-353d2c57f066.png)

**Comment by vadzz-dev** [comment]
this event doesn't have that parameter in cpp-sdk. I assume it's c# module related, isn;t it?

**Comment by FabianTerhorst** [comment]
The Parameter only exists when using async. The range between 100 and 200 is correct i think.

**Comment by vadzz-dev** [comment]
if you don't modify player.health getter which is also returning 100-200 by default then it's okay and can be closed

**Comment by Revyn112** [comment]
@vadzz-dev but player.health should be 0-100 or? 
![Screenshot_20200213_182156](https://user-images.githubusercontent.com/7781906/74460812-cde65100-4e8d-11ea-9597-b57298aa54f9.jpg)

**Comment by Revyn112** [comment]
after talking private to vadzz, the behavior was never changed after the poll.

So player.health is 100-200 officialy everywhere (c#/nodejs).
