### ISSUE TITLE
start, stop, restart server functions

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv#255]
First of all, I'm truly glad that we are able to controll resources.
I think it would be even better if we could do this with server side functions.

For example:
alt.restartResource("resourcename");
alt.startResource("resourcename");
alt.stopResource("resourcename");
alt.isRunningResource("resource-name")
alt.getResources() // return all resource name

**Comment by vadzz-dev** [comment]
Thought about it too, most likely will be implemented in near future

**Comment by FabianTerhorst** [comment]
Duplicate of #21

**Comment by Lekenthu** [comment]
New ideas:
alt.isRunningResource("resource-name")
alt.getResources() // return all resource name

**Comment by vadzz-dev** [comment]
Move future discussion to #21
