### ISSUE TITLE
For changing the settings of the server

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv#256]
It would be great if we could change the settings in server.cfg (f.e.: password changing, slot changing) by server-side function while the server is running. This can help the server owners if at the opening they don't want to stress the server too much. With this they can slowly change the slot.

**Comment by vadzz-dev** [comment]
That's not possible since some libs that we use do not allow to change stuff on runtime

**Comment by FabianTerhorst** [comment]
Slot change isn't possible yeah, but are you sure password isn't possible?
