### ISSUE TITLE
Please make resource events global instead of local

### ISSUE THREAD

**Issue by blackdog476** [altmp/altv#258]
**Is your feature request related to a problem? Please describe.**
We can't detect if a resource stops or starts. If we have resource A, B and C, we need to know in C resource if A or B stops. This is because we have ~20 resources with commands in it, but we use the CHAT resource's exported function to add new command. We pass the callback as argument, and it gets stored in that chat module locally (so its unaccessible from outside), so we can handle all commands from that chat resource. But if a random module gets restarted or stopped, we have to delete its command handler from the chat resource. This is why we need to detect resource stops from the chat resource.

**Describe the solution you'd like**
We would like to have an extra argument to the resourceStop/Start events that tells which resource's status has been changed.

**Describe alternatives you've considered**
It is also good if another event gets fired when a resource stops and it's not the current resource.

**Additional context**
This is the same request that has been already asked on the alt:V Discord's support channel.

**Comment by vadzz-dev** [comment]
anyResourceStart/anyResourceStop/anyResourceError will be available in the next build
