### ISSUE TITLE
[Bug] everyTick return undefined

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv#259]
`
disableControlTick = alt.everyTick(disableChatControl);
alt.log("disableControlTick: " + disableControlTick)`

At the example above, the return value of disableControlTick variable is undefined. Because of that I cant delete everyTick. I  would need a fix ASAP as I use this much and I have already rewrote my mod from the old solution.

**Comment by FabianTerhorst** [comment]
Isn't the function used to remove the callback, same as with alt.on.?

**Comment by Lhoerion** [comment]
@FabianTerhorst It has `clearEveryTick` function to remove it.
@vadzz-dev

**Comment by FabianTerhorst** [comment]
doesn't that just accepts the callback?

**Comment by Lhoerion** [comment]
`clearEveryTick(time: number|number)`

**Comment by Lekenthu** [comment]
Yes but doesn't working.
