### ISSUE TITLE
Add function to get client branch and version

### ISSUE THREAD

**Issue by datWeazel** [altmp/altv#266]
**Is your feature request related to a problem? Please describe.**
Sometimes different issues arise when a player joins with an older AltV client. I had multiple instances of people reporting problems and when asked they told me they used "beta" when in fact they didn't. Having the option to get client branch and version on clientside would help debugging.

**Describe the solution you'd like**
player.clientBranch
player.clientVersion

**Comment by FabianTerhorst** [comment]
Clients with old version and different branch shouldn't be able to connect when it will produce problems. When it's possible then it's a bug.

**Comment by vadzz-dev** [comment]
But people can connect only with the same branch the server use
And can't connect with build < server build

**Comment by vadzz-dev** [comment]
Yeah, Heron is right. Are you sure they conncet with another branch?

**Comment by datWeazel** [comment]
The situation where someone joined a beta server with stable client was a while ago. Maybe that is fixed now? 

But not so long ago someone joined with Client A where Server was version A+2 or smth. like that. (Both client and server where on beta branch but different builds.)

**Comment by 7Hazard** [comment]
Can this be reproduced? Otherwise it isn't really an issue. It should be possible to connect through other branches in the first place.

**Comment by 7Hazard** [comment]
It should be possible to connect through other branches in the first place.

If it is really so that players can connect to a server with mismatching branches, make an issue about that.
