### ISSUE TITLE
Show disconnection message

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv#271]
**Is your feature request related to a problem? Please describe.**
If you want to call native "SetWarningMessage" at "alt.on("disconnect") nothing happens and client is crashing (i think because of unload client resources).

**Describe the solution you'd like**
If somebody gets disconnected a "Warning Screen should appear with the reason of the disconnection automatically (with given parameters) or manually with alt function that not cause crashing client.

```
alt.SetWarningMessage(string: "Line1", string: "Line2", boolean: ShowBackground);

alt.SetWarningMessageWithHeader(string: "Header", string: "Line1", string: "Line2", boolean: ShowBackground);
```

**Additional context**
https://imgur.com/a/DxIo6kP

**Comment by Lhoerion** [comment]
Duplicate of #99
