### ISSUE TITLE
[Bug] CanPlayOnline() is not a function ...

### ISSUE THREAD

**Issue by bozoweed** [altmp/altv#275]
## Expected Behavior
should return if player is banned rockstar or not

## Current Behavior
 TypeError: game.canPlayOnline is not a function

## Possible Solution
fix native

## Steps to Reproduce
game.canPlayOnline()

i have try like this too 
alt.emitServer("RockstarBanStatus", game._0x5F91D5D0B36AA310())
TypeError: game._0x5F91D5D0B36AA310 is not a function

befor it's working great

**Comment by KifKick** [comment]
Native canPlayOnline renamed to networkGetRosPrivilege3

**Comment by tastydev** [comment]
You are using old native names. The alt:V team changed the natives api to: https://github.com/UnknownModder/gta5-nativedb-data/blob/master/natives.json

**Comment by vadzz-dev** [comment]
I suggest you to stop using social club related natives, they will be removed in the near future

**Comment by bozoweed** [comment]
i need it because i don't want accept rockstar's banned player ....

**Comment by bozoweed** [comment]
please let us this possibility :(
