### ISSUE TITLE
[Bug] Failed to create IStreamPlayer

### ISSUE THREAD

**Issue by kreuzundquer** [altmp/altv#276]
## Expected Behavior
There should be no error, i dont even know where this comes from.

## Current Behavior
Whenever PlayerX joins the Server in Streaming Range of PlayerY, PlayerX gets the following error message in client logs: 

> [20:06:34][Error] Failed to create IStreamPlayer for PlayerY Buffer create error. Invalid value

## Steps to Reproduce

1. Let PlayerX stand somewhere.
2. Let PlayerY spawn in Streaming Range of PlayerX

## Context (Environment)
Using Beta #789 and NodeJS on Client and Server.

**Comment by FabianTerhorst** [comment]
Check again if its fixed with latest version.

**Comment by kreuzundquer** [comment]
Checked today on #997 beta and it seems to be fixed. I will have an eye on it for the next weeks and will reopen the issue if it comes back. Thank you :)
