### ISSUE TITLE
[Bug] Custom props can't be spawned without ymap

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#277]
I got some custom 3d modelled props which don't spawn unless I'm near a ymap where those props are used. It's like GTA doesn't have them loaded internally until I'm near a ymap where those props are used and then they get loaded.
Natives like `isModelValid `also return false until then.
I can't load the models manually, tried to do it with `alt.loadModel` and `game.requestModel` but it doesn't have any effect.
The console doesn't show any errors (like loading failed).
The props (ydr's) and the ytyp are 100% correct. I tested the ecxact some models in FiveM and there it works without any problems so it has to be an alt:V problem.

## Expected Behavior
Props spawn normally _(after loading them)_.

## Current Behavior
Props don't spawn and can't be loaded.

## Steps to Reproduce
1. Get a custom prop
2. Try to load the model on the server via `alt.loadModel` or `game.requestModel` (won't work)
3. Try to spawn it on the server (also won't work)
4. Create a ymap with the model in it
5. Go to the ymap and try to spawn the prop again (this time it will work because GTA loaded the model because it's in the ymap)

**Comment by Lhoerion** [comment]
Can you post example resource to reproduce?

**Comment by Hardy535** [comment]
If the devs need an example resource I can send it to them via Discord.

**Comment by Hardy535** [comment]
Okay, it works now. I don't know why but without changing anything (not the props nor the config files) the props spawn.
