### ISSUE TITLE
[Bug] ColShape_IsEntityIn() always return false

### ISSUE THREAD

**Issue by LeShred** [altmp/altv#279]
ColShape_IsEntityIn() always return false

## Expected Behavior
ColShape_IsEntityIn() should return true when checked entity is inside a specific colshape

## Current Behavior
ColShape_IsEntityIn() always return false

## Steps to Reproduce
1. Enter a closhape
2. Call ColShape_IsEntityIn() with colshape player is in and check player

**Comment by FabianTerhorst** [comment]
Can you check if its working correctly now?

**Comment by LeShred** [comment]
Tested and noew working as expected.
Thank you
