### ISSUE TITLE
[Bug] altv not starting with new launcher

### ISSUE THREAD

**Issue by Kloppis** [altmp/altv#283]
## Expected Behavior
altv starting gta5 via new launcher and start altv

## Current Behavior
altv is not starting. error message: could not start gta5.
if you cklick ok tho its starting gta5 nomally without altv.

## Possible Solution
i have no idea what causes this bug so i would say:
1. find the problem
2. fix the problem

## Steps to Reproduce
1. download rockstar launcher from rockstar homepage
1. install gta5 in rockstar launcher
1. install altv
1. start altv

## Context (Environment)
this was a complete fresh installation of both gta5 and altv on an nearly new installed windows 10 pro 64.

## Detailed Description

nothing more to say than that

**Comment by FabianTerhorst** [comment]
You need to use beta branch for now.

**Comment by emcifuntik** [comment]
Beta merged to master. So issue fixed

**Comment by R3DIANCE** [comment]
seems like the issue still precise..
