### ISSUE TITLE
[Bug] Vehicle stream range problem

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#284]
There are 127 vehicles in stream range. When I create the 128th it doesn't appear.

Is it intentional? If so I don't understand the reason as there is no significant FPS drop when we are near these 127 vehicles.

**Comment by FabianTerhorst** [comment]
Thats gta's internal limit.

**Comment by Lekenthun** [comment]
Then we should be able to change streaming range. This needs solution as for a small town RP it isn't good. Here will be many vehicles at a small palce. Or the client should automatically delete the furthest and create the nearest.

**Comment by FabianTerhorst** [comment]
You can already change streaming range in server cfg.

**Comment by Lekenthun** [comment]
OK, but my other solution would be good.
