### ISSUE TITLE
[Bug] playerDamage is not triggered anymore

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv#289]
## Expected Behavior
playerDamage should give values about damage, attacker, weapon etc.

## Current Behavior
Is not triggered anymore.

## Steps to Reproduce
1.  
```
AltAsync.OnPlayerDamage +=
                (player, attacker, oldHealth, oldArmor, weapon, damage) => OnPlayerDamageHandler(player, attacker, oldHealth, oldArmor, weapon, damage);

public void OnPlayerDamageHandler(IPlayer player, IEntity attacker, ushort oldHealt, ushort oldArmor, uint weapon, ushort damage) {
    AltAsync.Log("OnPlayerDamageHandler triggered");
}
```

## Context (Environment)
Trigger this Event to get all damage that happens (like falling from high aboves, from drowning etc). 
(The Event WeaponDamage is only triggered if a weapon is do the damage, like intendend.)

**Comment by FabianTerhorst** [comment]
Can be closed, is related to async module.

**Comment by Revyn112** [comment]
Problem found
