### ISSUE TITLE
Improve / implement vehicle surfing sync

### ISSUE THREAD

**Issue by DurtyFree** [altmp/altv#29]
It would be great to have proper vehicle surfing enabled.
I think this image explains it good:

![grafik](https://user-images.githubusercontent.com/20757266/54479279-770a6e80-481b-11e9-8cbe-d4f5ce717317.png)

![grafik](https://user-images.githubusercontent.com/20757266/54479336-0d3e9480-481c-11e9-9731-aae2cbb10818.png)

**Comment by emcifuntik** [comment]
It's streaming problem, as I know. Thanks for report

**Comment by vadzz-dev** [comment]
I hope this problem got solved
