### ISSUE TITLE
Unable to get into vehicle

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#292]
Sometimes I can't get in to some cars. I want to get in as a driver or passenger and it seems like the game does recognise that there is a car. My character walks to the door and the animation starts like it wants to open it, however stops after moving its hand to the handle. It does nothing. The vehicle is open of course. It can be helpbe by going farther than the streaming distance and back. This is the only way I can get in.

**Comment by Lekenthun** [comment]
Video: https://www.youtube.com/watch?v=Fldz8uNEd-k&feature=youtu.be

**Comment by tastydev** [comment]
Experiencing this very often, too now.

**Comment by vadzz-dev** [comment]
@Lekenthun can you test it on the latest dev build?

**Comment by vadzz-dev** [comment]
Is it fixed in latest release?
