### ISSUE TITLE
[Bug] Player position sync bug

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#293]
Hello,

The problem is that we created a spectate system and the detachment part produces some interesting things. After the stop of the spectate the other players see the spectator as falling down (as you can see in the first video). It can be stopped when the spectator jumps once. We created the system by attaching player to player. It has zero problems (you can check it on the second video). We didn't used reconnect (it is disabled on the whole server). The pings shouldn't matter because as you can see, the problems cease to exists after the spectator jumps, but the average ping is 50-60, the highest is 100. The streaming distance isn't the problem as you can see on the 2nd video, and we put the player back to the starting position where he started to spectate (we do that from server side). The problem is in the detach part. 

Here are the 2 video:
1st: https://imgur.com/a/XNJLgDJ
2nd: https://youtu.be/5-e89lqvXmY

**Comment by Lekenthun** [comment]
Script: https://pastebin.com/DA1Nu849

**Comment by FabianTerhorst** [comment]
Can you try if its still not working when not using ```attachEntityToEntity``` because that native maybe creates desyncs.

**Comment by Lekenthun** [comment]
I've tried it before, but it doesn't work.
