### ISSUE TITLE
player.Health always returns a value of 150 [Bug] 

### ISSUE THREAD

**Issue by GalacticFalcon** [altmp/altv#296]
So i tested multiple times but every time **player.Health** returned a value of 150 instead of 200

it should return 200 by default

## Current Behavior
returns 150 instead of 200

i checked the value of **player.Health** manually set the health at 200 yet it returned 150 each time

**Comment by tastydev** [comment]
can not confirm this behaviour

**Comment by GalacticFalconYT** [comment]
Testing it like this 
other then that my health variable has a value of 200;

`player.Health = 200;`
`player.SendMessage("My Health" + player.Health);`
`player.SendMessage("My Max Health" + player.MaxHealth);`
`player.SendMessage("My Player Class Health" + pInfo.Health);`

Result 
https://postimg.cc/9wbjn4Rc

Now Without
`player.Health = 200;`

Same Outcome
https://postimg.cc/9wbjn4Rc

**Comment by GalacticFalconYT** [comment]
Tested it like this....

`player.Health = 200;`
`player.SendMessage("My Health " + player.Health);`
`player.SendMessage("My Max Health " + player.MaxHealth);`
`player.SendMessage("My Player Class Health " + pInfo.Health);`

Outcome
https://postimg.cc/v4z3xrRY

Tested it without 
`player.Health = 200;`

Same Outcome
https://postimg.cc/v4z3xrRY

**Comment by Lhoerion** [comment]
Is it only ``csharp-module` related or this occurs on `node-module` too?

**Comment by FabianTerhorst** [comment]
I had checked the module code and couldn't find something. I also didn't changed health since release. Maybe he sets it in async code.

**Comment by GalacticFalconYT** [comment]
@Lhoerion Only csharp and i am not using Async @FabianTerhorst

**Comment by Lhoerion** [comment]
I've checked this and it works on build #971
