### ISSUE TITLE
Get syncer of vehicle (serverside)

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#299]
**Is your feature request related to a problem? Please describe.**
If you want to control a vehicle with certain natives it only works for the player which is currently the syncer of the vehicle.
It would be neat to have a function serversided to get the player that is currently syncing the vehicle.

**Describe the solution you'd like**
A function for **IVehicle** like **GetPlayerSyncing** returning an **IPlayer** or **null** if no one is currently syncing the vehicle.

**Comment by ThomasMarangoni** [comment]
Can be marked as closed? Feature is implemented
