### ISSUE TITLE
[Bug]  OnPlayerDead Event is not triggered

### ISSUE THREAD

**Issue by FasdAR** [altmp/altv#301]
The OnPlayerDead event is sometimes not called. And always not called when drowned.

```
private void initEvents()
        {
            AltAsync.OnPlayerConnect += AltAsync_OnPlayerConnect;
            AltAsync.OnPlayerDead += AltAsync_OnPlayerDead;
        }
        private async Task AltAsync_OnPlayerDead(IPlayer player, IEntity killer, uint weapon)
        {
            Chat.emitAddMessage(player, true, "{FF0000} " + player.Name + "{FFFFFF} Умер от " + "{FF0000} " + killer.Type);
            Spawn(player);
        }
```

Build #809, Altv.Net - 1.16.4-beta, Altv.Net.Async - 1.16.1-beta.

![image](https://user-images.githubusercontent.com/23176494/66272264-0d61b880-e870-11e9-84cd-8f6cd3755b3a.png)

**Comment by FabianTerhorst** [comment]
Make sure your host, module and all nuget packages are updated.

**Comment by FabianTerhorst** [comment]
And check if its working with none async event.

**Comment by FasdAR** [comment]
All versions of the components described above, they are relevant.

none async event doesn't work.

**Comment by FabianTerhorst** [comment]
Can be closed, i removed the null check for killer, but there is no killer for death events like yours.

**Comment by FasdAR** [comment]
What to do with this events? 
Where there is no killer

**Comment by FabianTerhorst** [comment]
i know, thats why its not called, i removed the killer check now.

**Comment by FasdAR** [comment]
Okay, thanks
