### ISSUE TITLE
[Bug] GiveWeaponAsync or GiveWeapon, Interface Gta invisible

### ISSUE THREAD

**Issue by FasdAR** [altmp/altv#302]
When call GiveWeaponAsync or GiveWeapon, the GTA interface disappears. Only reconnect helps.

```
public static void getWeapon(IPlayer player, WeaponModel weaponModel, int ammoCount)
        {
            player.GiveWeaponAsync((uint)weaponModel, ammoCount, false);
        }
```

Server #809, Altv.Net - 1.16.4-beta.

**Comment by FabianTerhorst** [comment]
does it happen with none async call as well?
Can you screenshot "GTA interface disappears".

**Comment by FasdAR** [comment]
I'm an idiot, it was curve after respawn. 
Instead of the player.Model and player.Position I made respawn through player.Spawn, and everything works.
