### ISSUE TITLE
[Bug] Pattern not found 8b 15 ????

### ISSUE THREAD

**Issue by DaveTwitch** [altmp/altv#304]
I downloaded the Alt V Client from your Website. I downloaded the client ressources and then they said to me that i need to choose a folder, where my Grand Theft Auto V is installed. I choosed my steam folder : Steam-> Steamapps -> common -> Grand Theft Auto V. 10 Seconds later, a window opened.   (See screenshot) 
![altv bug](https://user-images.githubusercontent.com/56310872/66407295-41aeb380-e9ed-11e9-9085-79dee13d4a3b.png)
Maybe you can help me? Thanks a lot.

**Comment by FabianTerhorst** [comment]
Use beta client, can be closed.

**Comment by 7Hazard** [comment]
Beta will be merged into stable soon (hopefully)
