### ISSUE TITLE
[Bug] TireSmokeColor setter doesn't work 

### ISSUE THREAD

**Issue by FavouRYT** [altmp/altv#310]
## Expected Behavior
Set the Tire Smokecolor.

## Current Behavior
nothing, setter doesnt work.

## Possible Solution
n/a

## Steps to Reproduce
veh.CustomTires = true;
veh.TireSmokeColor = new Rgba(255, 0, 0, 255);
Alt.Log(veh.TireSmokeColor);  <- returns "0,0,0,255" instead of "255, 0, 0, 255"

**Comment by Revyn112** [comment]
This function is working, you have to set Vehicle Mod for Custom Tyre Smoke before.
