### ISSUE TITLE
[Bug] Unspawn vehicle with player inside

### ISSUE THREAD

**Issue by BaboocheAd** [altmp/altv#311]
Spawn a vehicle, get into the vehicle, unspawn the ped. The server crash

## Expected Behavior
The vehicle unspawn or an error/warning is shown in the console server side

## Current Behavior
The server crash with no error

## Possible Solution
The server should not crash

## Steps to Reproduce
- Spawn a vehicle
- Go with your ped in the vehicle
- Unspawn the vehicle server side

## Context (Environment)
- Windows machine
- Trying to unspawn the vehicle with a key when you are in the vehicle (doing a park script)

The best thing will be to unspawn the vehicle and put the player on walk, but you can also just block the action server side and throw an error without crashing the server

**Comment by FabianTerhorst** [comment]
Is it "Spawn a vehicle, get into the vehicle, unspawn the ped." as in your first description. Or 
"Spawn a vehicle. Go with your ped in the vehicle. Unspawn the vehicle server side" in your reproduce steps? Because that some different behavior.

**Comment by BaboocheAd** [comment]
I'm not sure to understand the difference (I'm not english native). But here the steps:
Spawn a vehicle server side
Go with your player ped in the vehicle (as driver)
Unspawn the vehicle server side (having your ped in driver seat)

=> The server crash

**Comment by vadzz-dev** [comment]
Is it still actual on beta?

**Comment by Lhoerion** [comment]
@vadzz-dev Tested it on #879 build, no crashes on vehicle destroy
