### ISSUE TITLE
[Bug] (clientside) promise rejections work incorrectly

### ISSUE THREAD

**Issue by nrzull** [altmp/altv#319]
Try to execute following code on client:
```
function doSomethingAsync(){
    return new Promise(function (resolve, reject){
        reject(new Error('something went terribly wrong!'));
    });
}

doSomethingAsync()
    .then(function (fulfilledResult){
        alt.log(fulfilledResult);
    })
    .catch(function (err){
        alt.log(err.toString());
    });
```
And you will get next in your console:
```
[16:38:03][Error] [V8] Unhandled promise rejection. TypeError: set is not a function
[16:38:03] Error: something went terribly wrong!
```
This code works fine in browsers and node (if you change alt to console).

## Expected Behavior
Do not print `Unhandled promise rejection. TypeError: set is not a function`

## Current Behavior
see above

## Steps to Reproduce

1.
1.
1.
1.

**Comment by vadzz-dev** [comment]
What is set? Are you sure this error comes from this code?

**Comment by nrzull** [comment]
Okay, things start more funny. We use webpack on clientside and when async code crashes, webpack handles it and throws an error "Unhandled promise rejection. TypeError: set is not a function". BUT. When I don't use webpack and any other bundlers, just execute the code that in first post without transpilling, it crashes the game. if you change reject to resolve then all will be ok

**Comment by vadzz-dev** [comment]
Fixed
