### ISSUE TITLE
Custom hair components not working

### ISSUE THREAD

**Issue by lameule123** [altmp/altv#321]
## Expected Behavior
DLC is working on solo player/other MP.

## Current Behavior
Custom Hair doesn't appear in game. 
Specific META is in stream.cfg
(SHOP_PED_APPAREL_META_FILE | ALTERNATE_VARIATIONS_FILE)

## Steps to Reproduce
Try to load DLC/META for Ped Variations

## Detailed Description
Ressource based on Soupiest hair pack.
https://www.sendspace.com/file/y1fzz2

Does not seem to work.

**Comment by yoranjj** [comment]
duplicate of https://github.com/altmp/altv/issues/268
