### ISSUE TITLE
[Bug] Retype username on faulty altv.cfg

### ISSUE THREAD

**Issue by DatMayo** [altmp/altv#325]
## Expected Behavior
Ignoring wrong config line

## Current Behavior
I need to enter my atlv nick every time

## Possible Solution
Jump over faulty lines and ignore them

## Steps to Reproduce
altv.cfg (missing a in false)

> branch: 'beta'
> build: '818'
> debug: 'flse'
> gtapath: 'D:\Programme\Rockstar Games\Grand Theft Auto V'
> ignoreLowPriorityProps: 'false'
> lang: 'en'
> lastip: '127.0.0.1:7788'
> name: 'DatMayo'
> netgraph: 'false'
> streamerMode: 'false'

**Comment by vadzz-dev** [comment]
Should be fixed in latest beta
