### ISSUE TITLE
[Bug] Username Input can Corrupt altv.cfg

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv#326]
If you put a ' or a : in your username into the alt:V-UI the altv.cfg will be corrupted on next start. Error is "Config parse error:key excepted". Other special characters seem to work. Escaping the character \ doesn't work.

## Expected Behavior
The Username should working with a ' or : in it.

## Current Behavior
A Username with a ' in it corrupts the config.

## Possible Solution
When entering a ' or a : into Username input field maybe escaping it with a \ and ignore the character then when parsing config.

## Steps to Reproduce
Out a ' or a : into the Username Input field.

**Comment by DatMayo** [comment]
Duplicate, see #325

**Comment by ThomasMarangoni** [comment]
It isn't a duplicate, you reported a bug that corrupted config lines should be ignored, I reported a bug which produces corrupted lines, over the ui. These are two completely different issues.

**Comment by DatMayo** [comment]
True, sry @ThomasMarangoni

**Comment by vadzz-dev** [comment]
Should be fixed in latest beta
