### ISSUE TITLE
Vue.js mouse events handling from child elements

### ISSUE THREAD

**Issue by wenddak1ng** [altmp/altv#333]
## Expected Behavior

In actually chrome build if I'm set @click or another mouse event to component, all child elements always handling this event
## Current Behavior

In 72 build (alt:V cef) has a trouble with handling events. If you clicking on elements which created by vue component, any mouse events may be willn't fire
## Possible Solution

Update CEF

**Comment by stpnov** [comment]
https://vuejs.org/v2/guide/events.html
`<div v-on:click.self="doThat">...</div>`

**Comment by wenddak1ng** [comment]
> https://vuejs.org/v2/guide/events.html
> `<div v-on:click.self="doThat">...</div>`

It's not as easy as it looks. All vue modifiers like `.native`/`.self`/`.prevent` etc doesn't fix this issue. I tried to add a user click listener and all clicks worked. This issue currently in this CEF version or by multiplayer authors' mistake

**Comment by stpnov** [comment]
Really a problem exists

**Comment by Lhoerion** [comment]
Duplicate of #430
