### ISSUE TITLE
Exporting mysql connection / pool crash [nodejs]

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv#334]
## Expected Behavior
Exporting mysql connection / pool crash [nodejs]

## Steps to Reproduce -> script
> import * as alt from 'alt';
> import mysqlModule from 'mysql';
> 
> var pool = mysqlModule.createPool({
> 		connectionLimit : 50,
> 		host     : 'localhost',
> 		user     : 'root',
> 		password : '',
> 		database : 'gtav'
> 	});
> 
> export default { pool };

**Comment by FabianTerhorst** [comment]
You can only export simple js objects between reources.

**Comment by FabianTerhorst** [comment]
Or did it happen in same resource?

**Comment by Lekenthun** [comment]
Használd így: https://pastebin.com/aA6tB6C8

**Comment by Xenius97** [comment]
@Lekenthun köszi

Solved
