### ISSUE TITLE
Player.spawn makes Player locally invincible after death

### ISSUE THREAD

**Issue by WhishN** [altmp/altv#338]
## Expected Behavior
player should not get locally invincible

## Current Behavior
On my Testserver if a player dies (got shot) and i revive it (multiple ways) using player.spawn() he gets locally invincible. Others see him dying but not the player that got shot a second time 

possible broken sync?

## Possible Solution
keep up the sync? :D

## Steps to Reproduce

1. get 2 player on a server
2. player A kills player B
3. player B gets revive (serverside using Player.spawn() and setting Health back to max
4. Player A kills Player B again
5 a) Player A sees how Player B dies
5 b) Player B gets no Damage at all and is Invincible to other Players damate

**Comment by Lhoerion** [comment]
Does it happen on latest beta build #1003?

**Comment by FabianTerhorst** [comment]
I think death players aren't synced correctly and require always a .spawn on death.

**Comment by FabianTerhorst** [comment]
Its same as #220

**Comment by WhishN** [comment]
Fixed it found a mistake wasnt alt:V problem
