### ISSUE TITLE
[Bug] MongoDB (and other dbs) - Event Loop performance issue

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv#343]
## Expected Behavior
Access time to the database will be shortened.

## Current Behavior
Each first query to the database in the event takes a very long time (up to 3 seconds).
```
[16:07:45] databaseTest | playerConnect | FIND  402
[16:07:46] databaseTest | playerConnect | CREATED       49
[16:07:51] databaseTest | eventFromClient | FIND        4922
[16:07:51] databaseTest | eventFromClient | CREATED     47
```

## Possible Solution
Workaround is this script in connection file:
```ts
// Make Mongoose Fast Again

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function fnHook(object, name) {
    (function(fn) {
        object[name] = async function () {
            await sleep(0)
            return fn.apply(this, arguments);;
        };
    }(object[name]));
}

const modelFunctions = [
    "deleteMany", "deleteOne", "find", "findById", "findByIdAndDelete", "findByIdAndRemove", "findByIdAndRemove", "findByIdAndUpdate", "findByIdAndUpdate",
    "findOne", "findOneAndDelete", "findOneAndRemove", "findOneAndUpdate", "replaceOne", "updateMany", "updateOne", "save"
]

const prototypeFunctions = ["delete", "deleteOne", "increment", "remove", "save"];

for(let i = 0; i < modelFunctions.length; i++) fnHook(mongoose.Model, modelFunctions[i]);
for(let i = 0; i < prototypeFunctions.length; i++) fnHook(mongoose.Model.prototype, prototypeFunctions[i]);
```
It's just hooking the model functions and adding ``await wait(0);`` before execute and with that moving it to main thread or idk... It's just working.
The point is that it'll broke the model results functions like .lean or other stuff and you have to implement all of them by yoursalfe.

You can also keep all db functions inside setTimeout 0 callback but it's look like shit in code.

This issue is not realted to mongodb or mongoose only. Same shit you can see in other db's like PostgreSQL.

## Steps to Reproduce

1. Use Mongoose.
1. Make onClient event (server) in which you call db
1. on connect emit this event from client
1. Check response time

## Context (Environment)
Db connection is one of the most importat things in many gamemodes.
Without the script it's seems to be bottleneck.

## Detailed Description
Tuxick already know the issue and i was chat with him.

![tuxickchat](https://i.paste.pics/f77d00a1de08f52216c6633b8fef5fe4.png?trs=83e7cc98497b787080b25d501d332166b4a379ca856281e6c1d0de86c13df753)

**Comment by vadzz-dev** [comment]
literally every asynchronous thing is currently perform not so well because of event loop, ye, will be fixed after some refactoring will be done to support multithreading in API

**Comment by MacieGx** [comment]
@vadzz-dev I see, thanks for anwser. Toxic asked me to add a github issue a few months ago. I was lazy and I did it only now. 🤒
