### ISSUE TITLE
Resource encryption change

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#344]
I think that 1 resource shouldn't be encrypted into 1 file on client-side. If some file is modified then the client has to download the whole. For example there is my phone system. It is 70mb because of the wallpapers and ringtones. If I change 1 letter only, all the 70 mb has to be downloaded. This isn't really good. Files should be encrypted seperately by alt:V.

**Comment by vadzz-dev** [comment]
They won't be encrypted one by one, for storing wallpapers just use asset-pack
