### ISSUE TITLE
Make WorldObject.pos return Vector3 instead of Object

### ISSUE THREAD

**Issue by Miep3r** [altmp/altv#345]
**Is your feature request related to a problem? Please describe.**
I tried extending the Vector3 class using prototypes and I had to find out that the pos Property of the WorldObjects does not return a Vector3 value

**Describe the solution you'd like**
Converting the pos Property to a Vector3 value

**Describe alternatives you've considered**
implementing a serverside method to get the distance between two entities / WorldObjects

**Additional context**
/

**Comment by Lhoerion** [comment]
Fixed https://github.com/altmp/altv-typings
