### ISSUE TITLE
Windows Up / Down + Tints Not Synced [Bug] 

### ISSUE THREAD

**Issue by TheSmilez** [altmp/altv#350]
Windows up and down are partially synced. `rollDownWindows` is properly synced while `rollUpWindow` and `rollDownWindow` (Individual Windows) are not. To properly test this, I've also included a window tinting function which gives me a visual representation of the window's status. Window tints are also partially synced 

## Expected Behavior
When calling `native.rollUpWindow` or vice-versa, it should sync with other players within the stream. Currently stream is set at 300.

## Current Behavior
The only function that is synced with players is `rollDownWindows` which rolls all the windows down at once. However, when rolling windows up or down individually, the sync breaks between clients.

## Possible Solution
Apply the same sync technique used for `rollDownWindows` in API.

## Steps to Reproduce
I will include the steps on how to test on a server between clients as well as the source code used for the window management script.

**1.** Spawn a vehicle and use the `/tint` command
**2.** Use the `/wdown` command to roll the windows down
**3.** Use the `/wup` command to roll the windows up

**Comment by emcifuntik** [comment]
It should not be synced, because you use natives. Use serverside vehicle fields and functions instead 
https://wiki.altv.mp/ServerJS:Vehicle::setWindowOpened
https://wiki.altv.mp/ServerJS:Vehicle::isWindowOpened
