### ISSUE TITLE
[Bug] setPedMovementClipset native are not fully working and sync.

### ISSUE THREAD

**Issue by lameule123** [altmp/altv#351]
## Expected Behavior
Many of the walking styles that are available on other modMP and functional do not work on alt: V
setPedMovementClipset is also not sync.

## Current Behavior
Some walking style works.

## Possible Solution
Limited choice in Walking Style + Utilization of SyncedMetaChange for synchronisation

## Steps to Reproduce
```
                    if (!native.hasClipSetLoaded(value)) {
                        native.requestClipSet(value);

                        var maxCount = 0;
                        while (!native.hasClipSetLoaded(value) && maxCount <= 255) { maxCount++; native.wait(2); }
                    }
                    native.setPedMovementClipset(entity.scriptID, value, 0.0);
```

Value to test for exemple:
- move_m@buzzed
- move_m@gangster@var_i
- move_f@hurry@a
- move_m@hurry@a

**Comment by vadzz-dev** [comment]
You're loading them wrong, native.wait is not working and never will, use setInterval instead

**Comment by tastydev** [comment]
better load thoose things through a promise, snippets can be found in the forums and discord
