### ISSUE TITLE
Resource downloads are slow in some cases

### ISSUE THREAD

**Issue by derRAV3N** [altmp/altv#352]
## Expected Behavior
In theory every client should use the available bandwidth to download resource files from a server.

## Current Behavior
In some cases, clients will only download with about 1Mbit/s or even less, this may be random and seems to be dependent on some factor on the hosting server.

## Possible Solution
Can't provide a solution, since this seems to be an internal alt:V problem or a problem with the OS or anything.

## Steps to Reproduce
I can't really tell, how to reproduce this, I didn't find a pattern until now.
I'm using Ubuntu Server 18.04 LTS as OS, hosting at Contabo. A friend of mine (Petrus#0001) is hosting at Contabo as well, but is using Ubuntu Mate 19.10 and doesn't have this issue. Another person (Btx#6910 on Discord) has the same OS and the same issue. Scurrows has this issue on Windows Server.
1. Add some resources which are >10MB file size.
1. Connect to that server, eventually let different people try it.

## Context (Environment)
People can't properly download resources provided by a server.

## Detailed Description
1. Sometimes a resource will load with the intended maximum speed and sometimes a resource will download really slow.
1. This issue appears per-resource. As in: You connect to the server, the first resource may be downloading fast, the next will be loading slow, and the following will be fast again. But most of the time, downloading resources are slow.
1. People can kinda get around this issue by cancelling a resource download when they see that it's loading slower than usual, then just connect again to the server and it will be a kinda 50/50 chance to load fast or slow.
1. I talked to my hosting provider (Contabo), who has unlimited traffic for it's users. They checked my server and i did a speedtest as well, and there is no throttling on their end. When I provide files through e.g. a webserver independent of alt:V, users can download files just fine at max speed.
1. There is another user on Discord (Btx#6910), who is having the exact same issue, I'm not sure if it's because of the same origin, as I don't even know the origin, but it seems like the only similarity between us two is, that we are both using Ubuntu Server 18.04.
1. I shared my code base to a friend of mine (Petrus#0001) to let him test this on his system and he doesn't have this issue.

## Possible Implementation
Can't provide a solution, since this seems to be an internal alt:V problem or a problem with the OS or anything.

**Comment by derRAV3N** [comment]
So, I'm not really sure what to do about this, but it's an ongoing issue for about 2 Months. I am not really sure if this issue was permanent or since some alt:V update, or Ubuntu update, or any update. I didn't have this issue with my **client**, but some people of my team did have slow downloads before, eventually that was because of this bug, or just random internet problems for them. About two months ago it started for me.

I contacted my provider last week to check for problems with him, since I thought they throttled me because I was having a little test on my server two months ago where quite some people downloaded many big resources, but they told and also checked manually if I am throttled, which I am not.

I can provide my server files to the team if they want to, I just don't really know what to check for now.

**Comment by Scurrows** [comment]
I can reproduce it. Dependent on connection quality (Like slow connection, vpn, ...) not only resource download is hard laggy. In our case all emits from server to client are very slow and took over 60 seconds for ~16kb. I've create a list about that. The download and upload speed of server and client is ~2 mbits.

[transfair.pdf](https://github.com/altmp/altv/files/3997614/transfair.pdf)

**Comment by derRAV3N** [comment]
Hmm, If it's on your system as well, that would rule out anything with Ubuntu I guess. Also, on my end, connection methods don't matter. My server has about 200/200 mbit/s and I have 400/200 mbit/s locally.

Also, since that is only a small testserver but with many resources to test, I can't say that emits are taking long. At this point normal emits with like 2 objects worked fine. Eventually gonna test it.

Also, it seems to me, is your issue permanent or also just from time to time? As I stated, sometimes for me, resources load at a good speed, it's like a 50/50 chance.

**Comment by Scurrows** [comment]
Its a known issue. Not only on my mashine. Its depend on connecction quality

**Comment by derRAV3N** [comment]
Interestingly a friend of mine with the exact same alt:V resources doesn't have these problems. All Clients can download the resources just fine.
He's Ubuntu Mate 19.10 (with UI), on Contabo as well.

**Comment by btx78000** [comment]
Hi, my users had the same issue, got very slow download with any type of internet connection, we can get more mb/s with canceling resources downloading and trying again and again. very strange :/, the behavior is present on our two dedicated servers

**Comment by derRAV3N** [comment]
I think with one of the latest updates, this issue got fixed.
@btx78000 @Scurrows Does it work for you again as well?

**Comment by Lhoerion** [comment]
I assume that this issue is fixed.
If the issue will appear again, just let us know in this issue.
