### ISSUE TITLE
Event gameEntityCreate is called before the entity position is set right

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv#357]
## Expected Behavior
gameEntityCreate will be called after setting correct entity position set.
## Current Behavior
 gameEntityCreate is called before the entity position is set right

## Steps to Reproduce

1. Create vehicle serverside, and send it to client.
1. In client watch gameEntityCreate
1. When you get your vehicle in gameEntityCreate event check the vehicle pos using getEntityCoords (vehicle.pos will return good position).

## Context (Environment)
When setting player in vehicle by watching gameEntityCreate and it's teleporting player to 0 0 0 (its not visible in game, only map zoom change and sometimes map arrow), it's also lagging for less than sec and textures look like they're loading up again.

## Detailed Description
https://streamable.com/7rx8p

**Comment by vadzz-dev** [comment]
Should be fixed in latest dev build
