### ISSUE TITLE
[Bug] isDiscordInfoReady() returns always true when discord was running on game startup

### ISSUE THREAD

**Issue by DurtyFree** [altmp/altv#359]
## Expected Behavior
`alt.isDiscordInfoReady()` should return false if discord is not running / got shutdown while alt:V is started.

## Current Behavior
`alt.isDiscordInfoReady()` returns true even tho discord is not running anymore / got shutdown while alt:V was running.

## Steps to Reproduce
1. Call `alt.isDiscordInfoReady()` -> returns true
2. Shutdown discord
3. Call `alt.isDiscordInfoReady()` -> still return true

**Comment by MacieGx** [comment]
As far i remember isDiscordInfoReady should not be used for checking is player have Discord running.

Its for checking is OAuth2 process is completed.

**Comment by DurtyFree** [comment]
@MacieGx What is `isDiscordOAuth2Accepted()` and `isDiscordOAuth2Finished()` then?

**Comment by MacieGx** [comment]
> @MacieGx What is `isDiscordOAuth2Accepted()` and `isDiscordOAuth2Finished()` then?

Right. I thought about it. My mistake.
