### ISSUE TITLE
Invisible vehicle

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv#365]
As you can see in the video, vehicles can bee seen from an angle, and disappear from an other.
Video: https://www.youtube.com/watch?v=6uQHQ70Jvj8&feature=youtu.be

We can repproduce it by teleporting the vehicle to us and the vehicle is not directly on the ground but above it instead

**Comment by ThomasMarangoni** [comment]
Any Vehicle or Specific?
You need to provide some more information.

**Comment by FabianTerhorst** [comment]
Can you check if it is still happening?

**Comment by Lekenthu** [comment]
No problem in last 1 month.

**Comment by Lhoerion** [comment]
It's possible that it was fixed on build #997, which addressed similar issue to this one.
If the issue will appear again, just let us know in this issue.
