### ISSUE TITLE
Passing parameters to atl:V launcher

### ISSUE THREAD

**Issue by alexnalivayko** [altmp/altv#374]
**Is your feature request related to a problem? Please describe.**
As a developer of one of the servers, I want to be able to pass parameters (for example, a Social Club authorization session) from my custom launcher to the alt:V client launcher. 

**Describe the solution you'd like**
It's hard for me to say, but I would like to get some kind of software API using it at the OS (Windows) level.

**Describe alternatives you've considered**
No alternative. Maybe, running program in silent mode using command prompt.

**Additional context**
The point of my proposal is that I want to get an authorization session on the side of my launcher, and pass it to alt:V client launcher to accept user, without his participation (for example, the login and password of Social Club are hard-coded in my launcher).

**Comment by FabianTerhorst** [comment]
You can use early auth in most cases. And i dont think we want to encourage servers to create a custom laucher by providing apis for it .

**Comment by alexnalivayko** [comment]
> You can use early auth in most cases. And i dont think we want to encourage servers to create a custom laucher by providing apis for it .

Do I understand correctly that the alt:V client launcher is waiting for authorization (and it doesn't matter that it is from Social Club Launcher)?

**Comment by FabianTerhorst** [comment]
Search in the discord for earlyauth.

**Comment by alexnalivayko** [comment]
I'm sorry, but it won't solve my problem. You offer a solution when connecting to the server, and I need a solution for connecting to the game itself.

**Comment by FabianTerhorst** [comment]
There is already a protocol for opening altv and automatically connect to a given server ip and port.

**Comment by FabianTerhorst** [comment]
e.g. ```altv://connect/ip:7788```, but might not work correctly right now.

**Comment by alexnalivayko** [comment]
Perfect, thanks!

But what should I do with the authorization transfer? My goal is to get the session on my side and pass it to your client launcher. The game should start with the session passed (socialId, etc.).

**Comment by FabianTerhorst** [comment]
Since there won't be a extra api for launchers to provide data to the game, you probably could only hope that it might be possible to add additional data to the connect protocol, because that can also be useful for websites filling login tokens for faster connect and login by clicking a button.

**Comment by alexnalivayko** [comment]
It sound good. Thank you for answers!

**Comment by 7Hazard** [comment]
alt:V does not condone usage of external launcher over alt:V. If you wish to improve connection to servers please post issues regarding early auth, resource downloading etc...
