### ISSUE TITLE
Game crash on pressing P button after F8 reconnect

### ISSUE THREAD

**Issue by pleum** [altmp/altv#377]
## Expected Behavior

Press P after reconnected should work fine

## Current Behavior

Game crash

## Possible Solution

N\A

## Steps to Reproduce

1. open the console with F8
1. type `reconnect`
1. press `P` on keyboard

## Detailed Description

alt:V Server, build #906, branch stable

**Comment by Lhoerion** [comment]
Does it happen on latest beta build #993?

**Comment by Lhoerion** [comment]
I assume that this issue is no longer present.
If the issue will appear again, just let us know in this issue.
