### ISSUE TITLE
Dimension Limits

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv#378]
**Is your feature request related to a problem? Please describe.**
According to VadZz the current dimension limits are this:
```
It's 2byte signed integer so 65535
From -32768 to 32767
```

I'd like to see a larger integer used for dimensions so we can lock interiors to dimensions and not have to re-evaluate our patterns. Binding a house interior to a dimension is as simple as it gets.

**Comment by derRAV3N** [comment]
Stuyk probably figured it out, but just for other people wondering why it goes into negative:

Dimensions > 0 can only see stuff in the same dimension
0 is main dimension and can only see 0
Dimensions < 0 can see 0 and stuff in the same dimension

Also 32k should be enough, there are about 1000 houses on the map and 4095 players support.

**Comment by tastydev** [comment]
We really need a integer here,  a signed short is not enough for really big gamemodes where u have to manage private factorys, motel rooms etc.

**Comment by derRAV3N** [comment]
Heron talked to me yesterday and told me it isn't even a short anymore and that's why Stuyk closed the issue.

**Comment by tastydev** [comment]
perfect
