### ISSUE TITLE
change Cursor internal state to bool instead of number

### ISSUE THREAD

**Issue by FavouRYT** [altmp/altv#379]
**Is your feature request related to a problem? Please describe.**
Sometimes error cursor cant go < 0 appear

**Describe the solution you'd like**
Change alt.showCursor internal to a bool instead of an internal number

**Comment by FabianTerhorst** [comment]
Cursor bool getter will be implemented afaik. Cursor state will remain a number.

**Comment by lameule123** [comment]
#331

**Comment by Lhoerion** [comment]
https://altmp.github.io/altv-typings/modules/_alt_client_.html#showcursor

**Comment by FabianTerhorst** [comment]
Duplicate.
