### ISSUE TITLE
Crash when getting imported exports from resource

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv#380]
## Steps to Reproduce
Working:
> import alt from 'alt';
> alt.log(alt);

Crash:
> import * as test from 'resource_name';
> alt.log(test);

**Comment by martonp96** [comment]
What kind of stuff are you importing? Cross resource import/export is very limited, for example you can't import a mysql connection from an another resource.

**Comment by FabianTerhorst** [comment]
Make sure to define resource_name as dependency.
