### ISSUE TITLE
Change resource stop order

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv#382]
## Expected Behavior
Change resource stop order from last to first or add resource stop order setting to resource.cfg or server.cfg

## Current Behavior
If you stop the server, resources will stop from first to last. This is not good because our mysql resource stops first, and other resources can't do queries after mysql is stopped.

Server log on start:
> [09:19:10] Loading resource v_mysql
> [09:19:10] Loaded resource v_mysql
> [09:19:10] Loading resource v_chat
> [09:19:10] Loaded resource v_chat
> [09:19:10] Loading resource v_whitelist
> [09:19:10] Loaded resource v_whitelist
> [09:19:10] Loading resource v_console
> [09:19:10] Loaded resource v_console
> [09:19:10] Loading resource v_admin
> [09:19:11] Loaded resource v_admin
> [09:19:11] Loading resource v_account
> [09:19:11] Loaded resource v_account
> [09:19:11] Loading resource v_notification
> [09:19:11] Loaded resource v_notification
> [09:19:11] Starting HTTP server on 0.0.0.0:7788
> [09:19:11] Server started

Server log on stop:
> [09:23:13] Stopping resource v_mysql
> [09:23:13] Stopped resource v_mysql
> [09:23:13] Stopping resource v_chat
> [09:23:13] Stopped resource v_chat
> [09:23:13] Stopping resource v_whitelist
> [09:23:13] Stopped resource v_whitelist
> [09:23:13] Stopping resource v_console
> [09:23:13] Stopped resource v_console
> [09:23:13] Stopping resource v_notification
> [09:23:13] Stopped resource v_notification
> [09:23:13] Stopping resource v_admin

**Comment by 7Hazard** [comment]
This was already fixed yesterday

**Comment by Xenius97** [comment]
@7Hazard  I'm using #955. And it doesn't work.

**Comment by Xenius97** [comment]
@7Hazard 
> [10:35:43] alt:V Server, build #955, branch beta
> [10:35:43] Starting Test Server on 0.0.0.0:7788
> [10:35:43] Loading resource v_mysql
> [10:35:43] Loaded resource v_mysql
> [10:35:43] Loading resource v_chat
> [10:35:43] Loaded resource v_chat
> [10:35:43] Loading resource v_whitelist
> [10:35:43] Loaded resource v_whitelist
> [10:35:43] Loading resource v_console
> [10:35:43] Loaded resource v_console
> [10:35:43] Loading resource v_admin
> [10:35:43] Loaded resource v_admin
> [10:35:43] Loading resource v_account
> [10:35:43] Loaded resource v_account
> [10:35:43] Loading resource v_notification
> [10:35:43] Loaded resource v_notification
> [10:35:43] Starting HTTP server on 0.0.0.0:7788
> [10:35:43] Server started
> [10:35:45] Stopping resource v_mysql
> [10:35:45] Stopped resource v_mysql
> [10:35:45] Stopping resource v_chat
> [10:35:45] Stopped resource v_chat
> [10:35:45] Stopping resource v_whitelist
> [10:35:45] Stopped resource v_whitelist
> [10:35:45] Stopping resource v_console
> [10:35:45] Stopped resource v_console
> [10:35:45] Stopping resource v_notification
> [10:35:45] Stopped resource v_notification
> [10:35:45] Stopping resource v_admin
>

**Comment by vadzz-dev** [comment]
@7Hazard you made it exactly opposite of what should happen :lmao:

**Comment by 7Hazard** [comment]
https://i.imgur.com/p4Ba052.png
This is how it should look if dependencies are set up correctly

**Comment by 7Hazard** [comment]
I see what he's referring to now, it's not the dependencies, the resource order specified in server.cfg
It is not viable to rely on that cause the server does not store the resources in a particular load order

**Comment by 7Hazard** [comment]
Dependency order fix merged in latest beta

**Comment by Xenius97** [comment]
Not fixed, Stable #1006

> [11:37:22] alt:V Server, build #1006, branch stable
> [11:37:22] Starting Hungary Life V - Roleplay [hl-rpg.eu] on 0.0.0.0:7788
> [11:37:22] Loading resource v_mysql
> [11:37:23] Loaded resource v_mysql
> [11:37:23] Loading resource v_chat
> [11:37:23] Loaded resource v_chat
> [11:37:23] Loading resource v_utils
> [11:37:23] Loaded resource v_utils
> [11:37:23] Loading resource v_whitelist
> [11:37:23] Loaded resource v_whitelist
> [11:37:23] Loading resource v_console
> [11:37:23] Loaded resource v_console
> [11:37:23] Loading resource v_textures
> [11:37:23] Loaded resource v_textures
> [11:37:23] Loading resource v_admin
> [11:37:23] Loaded resource v_admin
> [11:37:23] Loading resource v_notification
> [11:37:23] Loaded resource v_notification
> [11:37:23] Loading resource v_account
> [11:37:23] Loaded resource v_account
> [11:37:23] Loading resource v_realtime
> [11:37:23] debug: { realtime: updateForAll }
> [11:37:23] Loaded resource v_realtime
> [11:37:23] Loading resource v_realism
> [11:37:23] Loaded resource v_realism
> [11:37:23] Starting HTTP server on 0.0.0.0:7788
> [11:37:23] Server started
> [11:37:30] Stopping resource v_mysql
> [11:37:30] Stopped resource v_mysql
> [11:37:30] Stopping resource v_chat
> [11:37:30] Stopped resource v_chat
> [11:37:30] Stopping resource v_whitelist
> [11:37:30] Stopped resource v_whitelist
> [11:37:30] Stopping resource v_utils
> [11:37:30] Stopped resource v_utils
> [11:37:30] Stopping resource v_console
> [11:37:30] Stopped resource v_console
> [11:37:30] Stopping resource v_textures
> [11:37:30] Stopped resource v_textures
> [11:37:30] Stopping resource v_realism
> [11:37:30] Stopped resource v_realism
> [11:37:30] Stopping resource v_notification
> [11:37:30] Stopped resource v_notification
> [11:37:30] Stopping resource v_admin
>

**Comment by vadzz-dev** [comment]
it's not about stopping in reverse order they were started but about stopping dependants before stopping resource itself, so if you need to control start/stop order make sure to properly set resource deps
