### ISSUE TITLE
[Feature] Add ResetMetaData / HasMetaData

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv#386]
**Is your feature request related to a problem? Please describe.**
Resetting the data and or checking if the data is set. 
Currently the only way to reset is to set the null mvalue. 
Currently the only way to check if the data is set is by checking if its the null mvalue.

**Describe the solution you'd like**
```cpp
virtual bool ResetMetaData(StringView key) = 0;
virtual bool HasMetaData(StringView key) = 0;
virtual bool ResetSyncedMetaData(StringView key) = 0;
virtual bool HasSyncedMetaData(StringView key) = 0;
virtual bool ResetStreamSyncedMetaData(StringView key) = 0;
virtual bool HasStreamSyncedMetaData(StringView key) = 0;
```

**Comment by Hardy535** [comment]
I think an event like "**syncedMetaReset**" would also be helpful in addition to that.

**Comment by FabianTerhorst** [comment]
This is fixed in latest release.
