### ISSUE TITLE
Server Image on Server Browser

### ISSUE THREAD

**Issue by AteshM** [altmp/altv#389]
Hello, i know something about some design change on the Server Browser, anyway I would like if possible to have a server config option for "Server Logo" and "Server Ico", the two of them would work like this:
The Server Logo, a standard sized picture on the top of the server info panel
Actual Design:
https://i.imgur.com/nHmIGzD.png
"Design" with the Logo:
https://i.imgur.com/UL6tcck.png
I guess from here you understand my ideea, now about the server ICO:
Actual design:
https://i.imgur.com/h76NuDY.png
My ideea:
https://i.imgur.com/pskD2BW.png
Now about the ico, it would be nice to be with some opacitiy, not 100% but around 40% and when hover 60%. 
Another ideea:
Make the Start from the favorite button glow with gold or something when hovering and when favorited. You cant say that its working or not, its just click and nothing happens. 

Disclaimer: Please dont mind about the basic design, I just used Paint so the idea its important, now your Designer if im not wrong can work more on it =)
In my opinion it would make the AltV main screen more friendly.

**Comment by iamfronty** [comment]
Icons are not going to be introduced because they make server list a mess, but server logo/banners/callithoweveryouwantto are about to arrive with UI redesign _(soon)_
