### ISSUE TITLE
[Bug] Crash when imported script doesn't exist or has syntax error

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv#390]
## Current Behavior
Client crashes after a few seconds (or if you restart script multiple times)

## Steps to Reproduce
Import a non exist script in client side like this:
> import test from './nonExist.js';

![chrome_KVFcG1NosQ](https://user-images.githubusercontent.com/6568348/72669153-c9fe1500-3a2e-11ea-8f9d-364252cde5f8.png)
![GTA5_K9tGXeNNES](https://user-images.githubusercontent.com/6568348/72669154-c9fe1500-3a2e-11ea-9304-8ed2515ae99f.png)
![Launcher_OugvwxNda5](https://user-images.githubusercontent.com/6568348/72669155-ca96ab80-3a2e-11ea-9bea-f6ba9bb1ce5d.png)

**Comment by FabianTerhorst** [comment]
Also happens when importing client resources not just js files #330

**Comment by vadzz-dev** [comment]
can you check it out on latest beta build

**Comment by Xenius97** [comment]
When i got script error then crash is fixed. But if I import something from other resource and I restart that resource server crashes.

Example script:

v_utils:
> import alt from 'alt';
> 
> export function makeSalt(length) {
> 	var result = '';
> 	var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
> 	var charactersLength = characters.length;
> 	for ( var i = 0; i < length; i++ ) {
> 		result += characters.charAt(Math.floor(Math.random() * charactersLength));
> 	}
> 	return result;
> }
> 
> export default { makeSalt };

Other resource:
> import * as utils from "v_utils";
> 
> alt.setInterval(()=>{
> 	try {
> 		alt.log(utils.makeSalt(20));
> 	} catch(e){
> 		alt.log(e);
> 	}
> }, 1000);

**Comment by FabianTerhorst** [comment]
then this issue is fixed an #330 needs to get fixed.
