### ISSUE TITLE
[Bug] native.isVehicleDoorFullyOpen always return false

### ISSUE THREAD

**Issue by lameule123** [altmp/altv#394]
## Expected Behavior
Return true after utilisation of  native.setVehicleDoorOpen wich basically open vehicle doors.

## Current Behavior
Always return false;

## Possible Solution
No one since this is the only one native to get current vehicledoor statut

## Steps to Reproduce
1.  use native.isVehicleDoorFullyOpen. He return false to u.
1.  use native.setVehicleDoorOpen to open the doors
1 . use native.isVehicleDoorFullyOpen with correct door index. Still false.

I really need it for my clientside raycast vehicle interaction..

**Comment by lameule123** [comment]
**More information from Lhoerion:**
To return true, door needs to be at 0.9999998211860657 angle at least
when you open it with game.setVehicleDoorOpen max angle is 0.9821100234985352.

As Workaround he advice me to use getVehicleDoorAngleRatio > 0.98, That's work.

**Comment by gamelaster** [comment]
But this doesn't look like altv problem. Is this happening also in Single-player natives?

**Comment by lameule123** [comment]
This combination of native is used in Rage-MP/FiveM and GT-MP without problems.
When u'r opening the door with SetVehicleDoorOpen, door is supposed to be fully open afaik.

In singleplayer this snippets its working with ScriptHook.Net.

btw we can close this issue maybe since we have a fully functional workaround provided by Lhoerion.

**Comment by Lhoerion** [comment]
Tested it again in GTAV v1.0.18698.0 SP with ScriptHookVDotNet v3.0.2.0.

# Research
0. `1282` - script handle of Franklin's vehicle (Buffalo S)
1. `return Function.Call<float>(Hash.GET_VEHICLE_DOOR_ANGLE_RATIO, 1282, 0);`- used to get door angle ratio
2. `Function.Call(Hash.SET_VEHICLE_DOOR_OPEN, 1282, 0, 0, 1);` - used to open door immediately
3. `Function.Call(Hash.SET_VEHICLE_DOOR_OPEN, 1282, 0, 0, 0);` - used to open door normally
4. `return Function.Call<bool>(Hash.IS_VEHICLE_DOOR_FULLY_OPEN, 1282, 0);` - function that's topic of the issue

With calling functions 1 & 2, outputs was between 0.94-0.96, calling functions 1 & 3 gave me outputs below 0.98, all tested on almost flat surface relative to world, outputs can vary depending on surface rotation.
It seems that in normal situations, it isn't possible to get function 4 return true and with previous observations, to achieve that function 4 needs function 1 to return door angle above 0.9.

# Conclusion
So I highly doubt it's alt:V problem, it's possible that other mods had made some adjustments to this native function.

**Comment by FabianTerhorst** [comment]
Not a issue.
