### ISSUE TITLE
[Bug] Vue.js with webView dragable problem

### ISSUE THREAD

**Issue by targaryen94** [altmp/altv#399]
## Expected Behavior
webView
https://codepen.io/pasoevi/pen/ooOrpo

## Current Behavior
If I want to move any element then I'm not able to move it. Only the dragStart function runs, dragEnd, dragenter, dragleave, dragend, drop never.

## Possible Solution
I dont know..

## Steps to Reproduce
1. create Vue.JS html implemented (codpen code)
1. call webView
1. try move items

## Detailed Description
I creating webView with Vue.js, i cant moving items.. but in web browser good...
Altmp use chromium?

**Comment by FabianTerhorst** [comment]
I recommend to not use html5 drag drop api. Its less flexible and doesnt work in cef.

**Comment by targaryen94** [comment]
Okey but what do i use instead for drag and drop?

**Comment by FabianTerhorst** [comment]
There are a lot drag and drop implementations. You can use a existing one or write a own one. Just make sure its not using the html5 drag and drop api.

**Comment by targaryen94** [comment]
i tried a lot of drag and drop none works please send one that works. I tried to write and it didn't work either.

**Comment by FabianTerhorst** [comment]
One i know for vuejs is https://github.com/Astray-git/vue-dragula but that is outdated. Writing yourself isn't hard, just move the elements by using cursor position.

**Comment by targaryen94** [comment]
thank you this working.

**Comment by SomeDevil** [comment]
Or you can use [https://github.com/SortableJS/Vue.Draggable](https://github.com/SortableJS/Vue.Draggable) which works fine in CEF too

**Comment by FabianTerhorst** [comment]
Not a actual issue, html5 drag drop is just not working in cef.
