### ISSUE TITLE
OnPlayerDamage bone parameter

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#4]
Add a "bone" parameter (bone index) to "OnPlayerDamage" serverside to indicate which bone of a player got hit.

**Comment by Revyn112** [comment]
@vadzz-dev are there any plans to add this as parameter in near future? :)

**Comment by vadzz-dev** [comment]
body part was added to weapon damage event, player damage indicates all kinds of damage tho doesn't make sence to include bone, reopen if you think you need it

**Comment by ThomasMarangoni** [comment]
I think bone would be useful, with this information you can make a complexes medic system. And if no specific bone is hit, then the parameter should be null or something like that

**Comment by Lhoerion** [comment]
@ThomasMarangoni Weapon damage event is for complex medic system which you mentioned. Player damage event is for all kind of damage, so even explosion which doesn't hit specific bone.
