### ISSUE TITLE
[Bug] drawText "lag" when combined with getScreenCoordFromWorldCoord in alt.on("update")

### ISSUE THREAD

**Issue by yoranjj** [altmp/altv#40]
Code: https://pastebin.com/mwHzKjfz
Video: https://youtu.be/BVZPPwVlq1Q

I was told by gamie to create an issue so that you guys wouldn't forget :)

**Comment by yoranjj** [comment]
I was told by gamie to create an issue so that you guys wouldn't forget :)

**Comment by vadzz-dev** [comment]
That's not related to alt:V, you need to use setDrawOrigin to draw text in 3d
