### ISSUE TITLE
[Bug] F8 Console Output doesn't wrap in a new line when no space is in the output

### ISSUE THREAD

**Issue by derRAV3N** [altmp/altv#404]
See [this](https://imgur.com/a/uEkjcew).
When you log a really long string which is longer than the F8 Console and does not contain spaces, it will not wrap at the end of the console window, but will just continue beyond the bounds of the screen.

## Expected Behavior
The string should be wrapped somewhere at the end.

## Current Behavior
The string doesn't get wrapped and just continues.

## Possible Solution
There is some CSS value to prevent this from happening, I sadly currently don't know what it's called.

## Steps to Reproduce
1. `alt.log("putsomereallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallylongstringintothis")`

## Context (Environment)
Just sometimes some content gets cut. e.g. when using `Object.keys()`;

## Detailed Description
-

## Possible Implementation
-

**Comment by vadzz-dev** [comment]
this one should be fixed in latest beta build
