### ISSUE TITLE
Call unknown natives

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#41]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to call natives which are not "hardcoded" as functions (_correct me if I'm wrong_) which is a problem because there are **tons** of natives in the updates that currently can't be called in altV. A lot of examples can be found in the decompiled scripts. Those natives are not in NativeDB.

**Describe the solution you'd like**
Either add a function like _callNative(nativeHash, params...)_ or add all natives from the updates to the "game" module. Personally I think it wouldn't be a good way to request all natives that you need from those updates by telling you guys as most of the time when looking at natives from decompiled scripts I just like to test them, most of the time I don't know if it's the right one and if I need it so to have all natives available would be great.

**Describe alternatives you've considered**
You tell me :P

**Comment by Lhoerion** [comment]
Does it concern latest beta build #1003?

**Comment by Hardy535** [comment]
Since the native db was changed to the one of UnknownModder we have access to all those missing natives.
So as long as the native list gets updated when GTA adds new natives, this feature is not really necessary anymore.
