### ISSUE TITLE
Settable voice channel range

### ISSUE THREAD

**Issue by lameule123** [altmp/altv#411]
**Describe the solution you'd like**

I would like to have the possibility to change the vocal range in order to develop a whisper / shout system. In addition to the next vocal which includes the occlusion it would be really good and the vocal would become really viable and at the level of the functions proposed by a solution like TFR for Teamspeak.

PS: The current vocal is already of very good quality despite some concerns. Thanks to the whole alt team: V

**Comment by bozoweed** [comment]
personnaly i juste create an other voice channel with the new specified range and switch player in this one then remove older , working fine

**Comment by lameule123** [comment]
I've do the same as workaround.

Btw this feature can would be good for radio system.

**Comment by vadzz-dev** [comment]
Voice-chat related enhancements moved to #445
