### ISSUE TITLE
example voice-chat problem[Bug] 

### ISSUE THREAD

**Issue by targaryen94** [altmp/altv#414]
## Expected Behavior
..
## Current Behavior
resource starting got error:

[01:05:33] Loading resource voice-chat
TypeError: alt.createVoiceChannel is not a function

## Possible Solution
IDK

## Steps to Reproduce
start voice-chat example resource

## Detailed Description
i starting voice-chat but i got error..  its example script.

**Comment by FabianTerhorst** [comment]
Use new alt.VoiceChannel(...)

**Comment by corvinsoft-tothzs** [comment]
Thank you!

**Comment by targaryen94** [comment]
Thankyou working! :)
