### ISSUE TITLE
Node.js MySQL connection using resourceStop event

### ISSUE THREAD

**Issue by targaryen94** [altmp/altv#415]
## Current Behavior
I got error .. and no save.

## Steps to Reproduce

1. npm install mysql (project folder)
1. write onResourceStop in mysql save

## Context (Environment)
`
alt.on('resourceStop', () => {
    alt.Player.all.forEach((player) => 
    {
      var charID = player.getSyncedMeta('char:id');
      var data = {} // player data
      
      mysql.getConnection((err, connection) => {
              connection.query('UPDATE character SET ? WHERE id = ?', [data, charID], function (error, results, fields) {
                  if (error) throw console.log(error);
              })
          });
    })
  });`

server crash/stop/other save all player data.
 

## Detailed Description
I have problem... i using node mysql (npm install mysql) and server is shutdown then i got error message and no save.

The save function is good because if i leave(disconnect) server saved data.

Error in putty:

> altv-server: ../deps/uv/src/unix/stream.c:459: uv__stream_destroy: Assertion `!uv__io_active(&stream->io_watcher, POLLIN | POLLOUT)' failed.
> ./start.sh: line 4:  3771 Aborted    ./altv-server

## Possible Implementation
IDK

**Comment by FabianTerhorst** [comment]
Your mysql query operation is none blocking, so it won't stop the server from shutting down. You need to call the blocking operation.

**Comment by targaryen94** [comment]
We misunderstood each other, if i  do stopping  server.  The mysql no saving and we writing a save to the resourceStop but, not working.

**Comment by FabianTerhorst** [comment]
We did not missunderstood each other, the call inside the event handler is running the queue async and won't block the event handler. When all stop event handlers are finished it will stop the server.

**Comment by targaryen94** [comment]
okay it's my bad, thanks. Then this error  reason maybe earlier deleteing getSyncedMeta? If i do stopped server then immediately deleted getSyncMeta value?

**Comment by FabianTerhorst** [comment]
I told you how you probably can fix it already.

**Comment by Lhoerion** [comment]
I assume it's implementation error made by declarant.
Please before adding issue, make sure by yourself or by asking on discord proper channel if it's indeed a bug.
