### ISSUE TITLE
add event playerWeaponChange

### ISSUE THREAD

**Issue by tastydev** [altmp/altv#418]
**Is your feature request related to a problem? Please describe.**
To easily achieve AntiCheat or Attachment mechanisms it would be nice to have a serverside "playerWeaponChange" event

**Describe the solution you'd like**
`alt.on("playerWeaponChange", (player: alt.Player, oldWeapon: number, newWeapon: number) => {
 // Do what you want.
});`

**Describe alternatives you've considered**
Build your own EventListener

**Additional context**
-none

**Comment by FabianTerhorst** [comment]
Duplicate of #9
