### ISSUE TITLE
Suddenly client crash

### ISSUE THREAD

**Issue by Chris0x** [altmp/altv#419]
I was connected to my local dev server (win) and the game was running in the background
The client was running and connected like 30min and suddently it crashed
My char was only standing around and did nothing
Im using the newest client and server version

[altv_990_Steam_0x7ff6b9580000_c-05-02-2020 22-14-13.zip](https://github.com/altmp/altv/files/4162132/altv_990_Steam_0x7ff6b9580000_c-05-02-2020.22-14-13.zip)

**Comment by Lhoerion** [comment]
Contact on discord with more detailed information (if there's) and upload crashdump.
