### ISSUE TITLE
Client crashes on reconnect

### ISSUE THREAD

**Issue by kreuzundquer** [altmp/altv#426]
Client chrashes everytime we use reconnect in #997 beta.

## Expected Behavior
Should just reconnect fine

## Current Behavior
Crashes the client everytime

## Steps to Reproduce
1. Use the reconnect command in console

## Context (Environment)
Using #997 beta on win64 server

**Comment by DasNiels** [comment]
Can confirm, doesn't crash everytime for me but does pretty much 9 outta 10 times. Beta branch.

**Comment by Lhoerion** [comment]
Contact on discord with more detailed information (if there's) and upload crashdump.
