### ISSUE TITLE
I don't hear other players but myself in voice channel

### ISSUE THREAD

**Issue by inpex** [altmp/altv#429]
I hear myself as soon as another player is within range. The other player has the same event.

## Expected Behavior

Another player's hearing

## Current Behavior

I don't hear other players, I only hear myself. I hear myself in bad quality

**Comment by Lhoerion** [comment]
The issue is present in which branch?

**Comment by FabianTerhorst** [comment]
Make sure you don't have multiple microphones plugged in.

**Comment by inpex** [comment]
I have no other microphone, every other player has the problem.

**Comment by Lhoerion** [comment]
On which branch you were at the time when this issue happened to you?
How to reproduce?

**Comment by inpex** [comment]
Problems already solved in the update
