### ISSUE TITLE
weapon wheel disable doesn't work

### ISSUE THREAD

**Issue by targaryen94** [altmp/altv#434]
**Expected behavior**
disable weapon wheel 

**Current behavior**
If i disable the 37 control then the game didn't disable.

Code:
`native.disableControlAction(0, 37, true);`
 or 
`native.disableControlAction(27, 37, true);`

**Steps to reproduce**
try top code

**Context (environment)**
https://natives.altv.mp/#/0xFE99B66D079CF6BC

I'm read the description but i not find resolve. Outdated link in  description.
github.com/crosire/scripthookvdotnet/blob/dev_v3/source/scripting/Controls.cs

**Comment by derRAV3N** [comment]
Did you try to use this in alt.everyTick()?

**Comment by Lhoerion** [comment]
Disabling control actions needs to be done in loop.

Before posting an issue, **consult it** with community on appropriate channels on alt:V Discord, next issues similar to this one **will be closed without notice**.

**Comment by DasNiels** [comment]
Try disabling any of the number keys(1,2,3 etc). Should work. I accidentally stumbled upon this when trying to disable only the number keys. It also disabled the weapon wheel for me.

This was back on rage but I'm assuming it'll give the same results on altv
