### ISSUE TITLE
interiorProxies

### ISSUE THREAD

**Issue by Kmz-rash** [altmp/altv#435]
Trying to stream an interiorProxies.meta but it does not seems to work properly. This meta is needed when there is a lot of MLO's in the server to avoid the blinking/invisibility problem.
Sadly after trying a bit it seems the meta is not working on Alt:V

Firstly, you need to get the last interiorProxies.meta (e.g the one from mpheist3), you need to check the 'startfrom' value and change it (the one in mpheist3 is 1078) to another values that is at least 1090 or more.
Why 1090, because you need to increase add 11 (from the milo that are in the mpheist3) and add 1 more int to act like if this what a new dlc.
Some people don't bother and just put 2000 in FiveM and it seems to work.

**Expected behavior**

If it works, when you have at least 10+ MLO's in the server, you should not have player disappearing inside of some MLO.
e.g at each DLC from Rockstar this number should be increased to not be in conflict with the last dlc 
**Current behavior**

currently this is what i have in the interiorProxies.meta:
[![Screenshot from Gyazo](https://gyazo.com/ced47bbb4358dcc8f654ab3d58ab350e/raw)](https://gyazo.com/ced47bbb4358dcc8f654ab3d58ab350e)
And this is my stream.cfg:
[![Screenshot from Gyazo](https://gyazo.com/72bb8e9188854d2e306e35f04181c7b6/raw)](https://gyazo.com/72bb8e9188854d2e306e35f04181c7b6)
I'v try to make a resource from the meta or to add it to any MLO's resource that i had but it didn't seems to work.
i'v cleared server cache and people cleared it too.
**Possible solution**

I don't know.
**Steps to reproduce**

Add MLO's, make an interiorProxies.meta, go to some of the MLO's and see if people vanish after going trough some portals.
**Context (environment)**

People going invisible is the worth, no hardware issues have been detected from using that much MLO's.
**Detailed description**

I don't know
**Possible implementation**

I would be nice to know that if we make an MLO's ressource, we need or not an interiorProxies per resource to deal properly with that issue

**Comment by Kmz-rash** [comment]
[![Screenshot from Gyazo](https://gyazo.com/216f7eed13966569dcb33c18de380b96/raw)](https://gyazo.com/216f7eed13966569dcb33c18de380b96)
[![Screenshot from Gyazo](https://gyazo.com/849bb4fd47d8fdd789f7df33b04bdf2e/raw)](https://gyazo.com/849bb4fd47d8fdd789f7df33b04bdf2e)
[![Screenshot from Gyazo](https://gyazo.com/34e8deb8cab143457e28ff8211064167/raw)](https://gyazo.com/34e8deb8cab143457e28ff8211064167)
[![Screenshot from Gyazo](https://gyazo.com/5e69a051fe331454670d8e16b62ef99f/raw)](https://gyazo.com/5e69a051fe331454670d8e16b62ef99f)
[![Screenshot from Gyazo](https://gyazo.com/afbf0b839710f0102d3ae12b3022d643/raw)](https://gyazo.com/afbf0b839710f0102d3ae12b3022d643)

**Comment by Kmz-rash** [comment]
So i tested MLO from different creators and they all have the issue so i think there is a problem with the interiorproxies

**Comment by Kmz-rash** [comment]
Okay new test: I made an interiorproxies (or interiorProxies i tried both name) in each of my MLO resources. augmented the startfrom value of +1 and + number of milo each time.
i ended with the last resource to be at   <startFrom value="2162" />

I tried on my small vps and it was weird, game was not playing correctly, got a lot of fps drop and client console was showing this:
[![Screenshot from Gyazo](https://gyazo.com/c976a661195e64c0a5652a709810e68f/raw)](https://gyazo.com/c976a661195e64c0a5652a709810e68f)

https://i.gyazo.com/9b30fa78042c21fb8da4870d2822c03b.png
[![Screenshot from Gyazo](https://gyazo.com/494d9711aa62aade554a95a7518de1ca/raw)]
(https://gyazo.com/494d9711aa62aade554a95a7518de1ca)
https://i.gyazo.com/494d9711aa62aade554a95a7518de1ca.png
https://i.gyazo.com/76d7e6dbd6723c5577389c76a09e7bf0.png

here is the exemple of my interiorproxies for the taxi MLO, the stream.cfg from this ressource and how the ressource is made. Hope this will help.

**Comment by Lhoerion** [comment]
@Kmz-rash You shouldn't define meta files as asset files and you did that with `stream/*`, that's the reason for console errors.

**Comment by Kmz-rash** [comment]
created peds as you asked @Lhoerion 
[![Screenshot from Gyazo](https://gyazo.com/6e1410a1b4b86c22ade7f44a6cd5c77b/raw)](https://gyazo.com/6e1410a1b4b86c22ade7f44a6cd5c77b)

they have the same problem as player

**Comment by Kmz-rash** [comment]
i'm gonna redo the resource in to avoid the problem with stream/*
gonna make a subfolder with assets and dumb file in it, interiorproxies will still be in stream/interiorproxies to see if it solves problems.

**Comment by Kmz-rash** [comment]
I disabled half of my mlo, the problems is still there, fps issues got better with restarting the vps (so may not be related to this issue). 
https://i.gyazo.com/a05f98d120fd7f6d9205367741831638.mp4

current max:   <startFrom value="2052" />

**Comment by Kmz-rash** [comment]
i'v made a new test: all the mlo and the interiorproxies.meta in one big resource. problem is still there
https://i.gyazo.com/8528e741195af01eeb6333bb9ddf1ff1.mp4

**Comment by Kmz-rash** [comment]
things i notice too, voice from the alt voice resource is not working whilte entering a custom mlo.
Outside everything is nice but when you enter it's fucked up

**Comment by vadzz-dev** [comment]
Does the same meta work in SP?

**Comment by Kmz-rash** [comment]
I didn't try in SP but it work for sure in FiveM

**Comment by lameule123** [comment]
Same problem for me.
When u have some on u'r server MLO people start to disappear inside and vocal encounter some bugs.
Position of player is not updated when entering in it for local client(and vocal) player is still outside the MLO.

interiorProxies doesn't work as described.

**Comment by Lhoerion** [comment]
Last time we tested with @Kmz-rash, it seemed that the game limit was the problem
We tested it using resources with one MLO & multiple MLOs (both had proper interiorProxy.meta) and chosen MLO (as test subject) was free of above issues, when it was the only custom one (as opposite to multiple MLOs).

**Comment by vadzz-dev** [comment]
Omg, i just missclicked

**Comment by vadzz-dev** [comment]
It worths checking the client.log if there're aby errors about game pools

**Comment by SandDanGlokta** [comment]
any news on this case? we also have this problem with arround 38 custom mlos.

**Comment by Kmz-rash** [comment]
latest dev build seems good with 4 people, we still need a bigger scale test to confirm that everything is good

**Comment by Revyn112** [comment]
We can't confirm this. tested with 8 players and around 80 interiors.

**Comment by SandDanGlokta** [comment]
we can also confirm , that with the dev branch and interiorproxies the clipping player problem is gone. we had 4 players testing it with 38 MLOs. dont know about more players. need to be testet. but, you could , if you like, merge / push the dev branch to rc.

**Comment by Revyn112** [comment]
So little update on here, we can confirm this problem is **fixed**.
Tested with 16 players and around 80 MLO.

BTW: We didn't streamed the interiorproxies right. It seems that there was some missinformation some time ago about this.

**Comment by Kmz-rash** [comment]
Quick question, is there a resource size limit (not the 16mb) and is there a number of ymap limit inside the interiorproxies?
