### ISSUE TITLE
Voice continuous transmission

### ISSUE THREAD

**Issue by bozoweed** [altmp/altv#437]
we need voice continue transmition for my project and if player  use push to talk and not whitlisted for that kick him because N key is for talking into radio systeme and is better way to counter meta gaming like say to his friend on discord "they have some cops don't coming" and cops don't ear anything 
thanks vadzz and lheorion for your time :)

**Comment by FabianTerhorst** [comment]
You can manage voice channels serverside, so its already possible

**Comment by vadzz-dev** [comment]
xd, @FabianTerhorst you just don't get him, we just discussed it in dm

**Comment by vadzz-dev** [comment]
an issue is about implementing a way to force voice activation with player's permission

**Comment by dexslab** [comment]
Cant you just run alt.enableVoiceInput() on connectionCompleted or something of that nature

**Comment by vadzz-dev** [comment]
@dexslab he knew some insides before #1004 was released, since we respect players privacy, it's not possible anymore to just enable players mic when you want to

**Comment by dexslab** [comment]
HORRAY for Privacy i am so glad to hear this as i would be pissed if a server i was on did this

**Comment by bozoweed** [comment]
@vadzz-dev my microphone still not work in my server . with voice detection activate or whitout it's same thing alt.log(alt.Player.local.micLevel) return 0

and how to force disable now ? exemple player is dead so i don't want let him speak

**Comment by vadzz-dev** [comment]
@bozoweed that's not a good place to discuss that, move to discord

**Comment by vadzz-dev** [comment]
I've merged voice-chat feature requests in #445
