### ISSUE TITLE
Make gameconfig.xml streamable

### ISSUE THREAD

**Issue by rethon82** [altmp/altv#444]
The gameconfig.xml contains some crucial upper limits regarding modded cars, mlos and so far. Having this file streamable would be very helpful for servers that rely heavily on custom interiors and cars.

The client crashes if more than approximately 60 custom interiors are loaded. It crashes with an error claiming a "pool is full".

There seems to be a solution to this problem. FiveM and even RageMp ran into the same issue. The Solution for fivem was allowing to stream the gameconfig.xml. Ragemp hat announced a streamable in the presumed upcoming 1.0 release.

A solution would be a system that allows to stream a custom gameconfig.xml.

I realize this is a crucial feature for the most upcoming servers. As modding is just beginning to start and will increase in the upcoming months, more and more developers will run into these limits.

**Comment by emcifuntik** [comment]
It's not possible, cuz engine loads gameconfig on game start to preallocate pools. We can't reallocate pools in game process, so it will not be done.
