### ISSUE TITLE
Voice chat - button disable

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv#447]
The voice button can not be disabled. It would be much better if the toggleGameControls function would disable it (or we had a custom function for disabling it) because if I write the letter N in the chat, the voice activates.

**Comment by vadzz-dev** [comment]
I'd make toggleGameControls disable voice chat in next beta build

**Comment by FabianTerhorst** [comment]
toggleGameControls shouldn't disable voice. There should be another method to do that, or handle that in webview when having inputs focused.

**Comment by derRAV3N** [comment]
i also think that toggling it with toggleGameControls is a bad solution. many servers use this to disable input when typing stuff in chat or opening an inventory, so you would essentially be muted when opening any window..

**Comment by Lekenthu** [comment]
Done. (toggleVoiceControls)
