### ISSUE TITLE
Game text flickers on everyTick

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv#454]
**Current behavior**
If you draw a text in everyTick and attach it to an entity then text flickers.

**Steps to reproduce**
Draw a text in game and attach it to an entity with getPedBoneCoords or getEntityCoords && getScreenCoordFromWorldCoord
> function drawText(text, x, y, scale, r, g, b, a, outline) {
> 	game.setTextFont(0);
> 	game.setTextProportional(0);
> 	game.setTextScale(scale, scale);
> 	game.setTextColour(r, g, b, a);
> 	game.setTextDropShadow(0, 0, 0, 0, 255);
> 	game.setTextEdge(2, 0, 0, 0, 255);
> 	game.setTextCentre(1);
> 	game.setTextDropShadow();
> 
> 	if (outline) game.setTextOutline();
>  
> 	game.beginTextCommandDisplayText("STRING");
> 	game.addTextComponentSubstringUnk(text);
> 	game.endTextCommandDisplayText(x, y);
> }

**Detailed description**
https://puu.sh/Fe1w4/e7c361c22f.mp4

**Comment by ThomasMarangoni** [comment]
You need to add the entity velocity and calculate the new position of the name tag. This is not a Bug it's a Math/Physics problem. Look on discord in #snippets, a post from tuxick, where a fix to this problem is.

**Comment by DurtyFree** [comment]
Its not a bug, please use setDrawOrigin + this calculation from tuxick to improve it even more: https://discordapp.com/channels/371265202378899476/583109900024938527/663356535413669888
