### ISSUE TITLE
Bullets are not synced (or not perfectly)

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv#455]
If you shoot a door or a prop then it has no effect for other players.

I've tested with doors, recorded from two different PC.
Camera1:
https://puu.sh/Fe1Gu/ed5c3d8949.mp4
Camera2:
https://puu.sh/Fe1Go/4a9f6cbbff.mp4

**Comment by FabianTerhorst** [comment]
This isnt a Bug. To reduce Network useage bullets that arent targeted to a entity arent synced perfectly.

**Comment by Xenius97** [comment]
pc1: https://puu.sh/Fe1Pd/41b145d77c.png
pc2: https://puu.sh/Fe1NO/86cf32a3cd.jpg

**Comment by FabianTerhorst** [comment]
That is how it should be.
