### ISSUE TITLE
MemoryBuffer methods have wrong typings

### ISSUE THREAD

**Issue by indilo53** [altmp/altv#457]
Following the docs and TS hints, I should pass a second value when reading, I tought it was somewhow a 'default' value in case of failure but nope.

**Expected behavior**
Compile fine without ts-ignore stuff

**Current behavior**
Need to ts-ignore the lines to force one parameter and it works

**Possible solution**
Fix typings

**Steps to reproduce**
Respect typings like this one : buffer.int(0, 0) => Error one arg expected

**Comment by Lhoerion** [comment]
`  export class MemoryBuffer {
    constructor(size: number);

    public byte(offset: number, value: number): number;

    public double(offset: number, value: number): number;

    public float(offset: number, value: number): number;

    public int(offset: number, value: number): number;

    public long(offset: number, value: number): bigint;

    public short(offset: number, value: number): number;

    public string(offset: number, value: number): string;

    public ubyte(offset: number, value: number): number;

    public uint(offset: number, value: number): number;

    public ulong(offset: number, value: number): bigint;

    public ushort(offset: number, value: number): number;

    public free(): boolean;
  }`
They've already two parameters

**Comment by indilo53** [comment]
Yes but somehow it wants only one parameter

**Comment by Lhoerion** [comment]
I've checked this right now and my IDE (Jetbrains Rider) recognizes method parameters and TS transpiles properly to JS.
Can you verify if this is indeed typings related?
Check also if your npm package is up-to-date.

**Comment by indilo53** [comment]
Yes it is up to date. It transpile properly to JS but at **runtime** I have an error saying it needs only one argument, I should have been more clear about that. So either I put the right number of arguments which is 1 and it does not transpile or I put the required by TS number of arguments (2), it transpile but runtime error (Error: 1 arg expected)

**Comment by indilo53** [comment]
So this work : 
`// @ts-ignore`
`buffer.int(0)`

this does not work:
`buffer.int(0, 0)`

**Comment by Lhoerion** [comment]
It's error in typings indeed, only `MemoryBuffer.string` have two parameters, will be fixed in next update.

**Comment by indilo53** [comment]
Okay :)

**Comment by Lhoerion** [comment]
Fixed in https://www.npmjs.com/package/@altv/types/v/1.0.15 release
