### ISSUE TITLE
HandlingData not working with streamed mod cars

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv#461]
**Expected behavior**
Getting the right handling data for a streamed modded car.

**Current behavior**
Getting error because model not exist.

**Steps to reproduce**
1. Spawn Modded Vehicle.
2. Execute Code to get Handling Data.

```
const vehicle = player.vehicle;
alt.log("Vehicle: " + vehicle.scriptID);
alt.log("Value: " + alt.HandlingData.getForModel(vehicle.model).acceleration.toString());
```
3. Getting Error: Error: model doesn't exist

**Context (environment)**
Tweaking Vehicle Handling Data on the fly for complex tuning system.

**Comment by FabianTerhorst** [comment]
Duplicate of #403
