### ISSUE TITLE
IVehicle.SetWindowOpened setter working partly

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv#464]
**Expected behavior**
Setting Window Opened or Closed.

**Current behavior**
SetWindowOpened works only for opening specific window. Closing the same window didn't working.

**Steps to reproduce**
1. SetWindowOpened(0, true);
1. SetWindowOpened(0, false);

**Context (environment)**
Complex Vehicle Controlling and Management System.

**Comment by FabianTerhorst** [comment]
Duplicate of #459. So it happens in node and c# module.
