### ISSUE TITLE
isVisible WebView Property not working

### ISSUE THREAD

**Issue by lameule123** [altmp/altv#466]
**Expected behavior**
Set display of webview to off when set to false.

**Current behavior**
Nothing

**Possible solution**
Alot but this one is the most simple in alot of case.

**Steps to reproduce**
- Create a webview
- Set isVisible to false
- No change

**Comment by Lhoerion** [comment]
Duplicate of #335

**Comment by SandDanGlokta** [comment]
needs a fix urgently
