### ISSUE TITLE
getShapeTestResultEx not working (Vector3 pointer)

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#47]
Calling the function **game.getShapeTestResultEx** for raycasting is not working.

## Expected Behavior
Return the raycast result for the pointers of the native.

## Current Behavior
Console is just outputting: `[Error] Native call failed: 0xcfcd44`

## Possible Solution
Fix it ples

## Steps to Reproduce

1. Call a raycast (START_SHAPE_TEST_LOS_PROBE for example) and get the returned raycast id (working)
2. Call game.getShapeTestResultEx (_GET_SHAPE_TEST_RESULT_EX) with the raycastID and some useless parameters as most of them are pointers

**Comment by Hardy535** [comment]
It seems like this won't work as one of the parameters is a **Vector3 pointer** which doesn't seem to be supported yet.

**Comment by vadzz-dev** [comment]
Fixed
