### ISSUE TITLE
Procvide "clientReady" event on client

### ISSUE THREAD

**Issue by c0nnex** [altmp/altv#472]
Scenario:
User connect to server , downloads 2 client-resources:
one containing scripts 
one containing only mlo's (biiiig)

**Expected behavior**
Scripts are not started before mlo's are loaded and initialized

**Current behavior**
Scripts are already running (onResourceStart called) even if the mlo's are still being initialized/loaded
There is literally no way to tell the server when the user is ready to go. This can lead e.g. to the user being kicked because of login timeout if loading of the mlo takes too long

**Possible solution**
provide a alt.on('clientReady',()) event to tell the scripts that the user is ready to go

**Comment by vadzz-dev** [comment]
There's alt.on('connectionComplete' event, lemme know if it fits your needs

**Comment by c0nnex** [comment]
Oh lol missed that one .. that should do the trick.
the scripting wiki really need more overview ;)
