### ISSUE TITLE
Native function removeModelHide doesn't work

### ISSUE THREAD

**Issue by DurtyFree** [altmp/altv#479]
I am using createModelHide native to hide objects ingame which works great, but removeModelHide doesnt. I have done some research and it seems like this native didnt work for anybody. But I have seen when I do reconnect in console, alt:V manages to recreate those hidden models so there must be some way to make them visible again.

**Expected behavior**
removeModelHide should make objects previously hidden with createModelHide visible again.

**Current behavior**
The native doesnt seem to do anything but on reconnect all hidden models are visible again.

**Steps to reproduce**
Hide any object InGame (see my attached log below for some example objects) with createModelHide & try to make it visible again using removeModelHide.

**Detailed description**
Here is some showcase of the native working on raycasted entities (that return handle) 
http://gyazo.com/38249f8d01aee5913c9e68b379ab7848

And here a showcase of it it even working for objects that dont return a handle with getClosestObjectOfType
http://gyazo.com/d6ba95101eb96d33d201ed23824a9da1

Image of my log while testing
![Image](https://i.imgur.com/iXGz7PC.png)

I have tried every possible combination of native parameters, heres a snippet from decompiled scripts how it should work:
![Image](https://i.imgur.com/6IoSAkQ.png)

And heres a full log of my testing with some example object positions & models: https://pastebin.com/YP71tU1g

**Comment by Lhoerion** [comment]
~Added~/fixed/~changed~ in build #1142
