### ISSUE TITLE
[Bug] drawText render limit when placed in 3d world (max 32 per frame).

### ISSUE THREAD

**Issue by yoranjj** [altmp/altv#48]
I tested this yesterday by placing a shitton of text labels in the 3d world and only displaying them when you're in range of them. Apparently, the labels start disappearing when you hit the 32 mark so I believe there's a limitation of 32 text labels per frame.

This might be a bug in alt as I talked to Hazard about it and he told me that I might as well make an issue out of it.

There's more information about it here (and other possible client limits); https://forum.fivem.net/t/guide-v-and-fivem-limitations/48493

**Comment by emcifuntik** [comment]
There is no reason to increase this limit.
