### ISSUE TITLE
getEntityModel not always working

### ISSUE THREAD

**Issue by c0nnex** [altmp/altv#481]
Standing in front of an ATM -Prop 
atm is at 287.3457, -1256.6, 28.44077
Doing a raycast, returns an entity was hit at that position.
Doing getEnittyModel/getEntityType on returned entity fails.

**Expected behavior**
model / type / position should be returned correctly

**Current behavior**
[Error] Native call failed: getEntityModel
getEntityType returns 0
getEntityCoords returns nullvector

**Steps to reproduce**
 alt.nextTick(() => {
                    var LocalPlayerID = alt.Player.local.scriptID;
                    var startPoint = alt.Player.local.pos;
                    var aimPoint = AddVector3(startPoint, game.getEntityForwardVector(LocalPlayerID));
                    var endPoint = Vector3Lerp2(startPoint, aimPoint, 4);
                    var rayCast = game.startShapeTestCapsule(startPoint.x, startPoint.y, startPoint.z, endPoint.x, endPoint.y, endPoint.z, 2, -1, LocalPlayerID, 7);
                    var [_, didHitEntity, coords1, coords2, hitEntity] = game.getShapeTestResult(rayCast, false, null, null, 0);
                    game.drawLine(startPoint.x, startPoint.y, startPoint.z, endPoint.x, endPoint.y, endPoint.z, 0, 255, 0, 255);
                    if (didHitEntity) {
                        var model = game.getEntityModel(hitEntity);
                        var entPos = game.getEntityCoords(hitEntity, true);
                        var entType = game.getEntityType(hitEntity);
                        var entRot = game.getEntityRotation(hitEntity, 2);
                        alt.log("TICKHIT ", hitEntity, model, entType, entPos, coords1);
                    }
                });

**Context (environment)**
release #1032
Also tested outside tick, same results

**Comment by Lhoerion** [comment]
You can't get entity model from map object like building shell etc., any try will result in native call failed on alt:V and crash on ex. ScriptHookV.NET. Some ATMs are placed into the wall, which can cause that ATM couldn't be fetched by raycasting or sometimes building shell (wall) is returned.
For now I close this issue, if you'll indeed confirm that getting entity model fails on ATM, I'll reopen it.
