### ISSUE TITLE
hasAnimDictLoaded never returns true

### ISSUE THREAD

**Issue by c0nnex** [altmp/altv#483]
Trying to play an Animation using taskPlayAnimation.
Code:

```
 alt.onServer("ANIMATION", () => {
     var ped = alt.Player.local;
     if (ped != null && ped.valid) {
         alt.nextTick(() => {
             var animDict = "cover@idles@unarmed@low@_a";
             while (!game.hasAnimDictLoaded(animDict))
                 game.requestAnimDict(animDict);
             game.taskPlayAnim(ped.scriptID, "cover@idles@unarmed@low@_a", "low_walk_l", 8, 10, -1, 1 | 2147483648, -8, true, true, true);
         });
     }
 });
```

gta will become unresponsive immediately and never wake up again.
check shows 
game.hasAnimDictLoaded(animDict)
never returns true

**Context (environment)**
release #1071

**Comment by vadzz-dev** [comment]
You're using it wrong, you need to check if it's loaded in everyTick like:
`game.requestAnimDict()
const timer = alt.everyTick(() => {
  if (game.hasAnimDictLoaded()) {
    alt.clearEveryTick(timer)
    // it's loaded here
  }
}`

**Comment by c0nnex** [comment]
I would have used it correctly if this would have been documented somewhere.

**Comment by Lhoerion** [comment]
@c0nnex Good luck with documenting usage of approx. 5200 natives in GTAV

**Comment by vadzz-dev** [comment]
@c0nnex well, it's general gta 5 thing so there's a lot of tutorials on the internet
