### ISSUE TITLE
Wheel variations wrong when using serverside api

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#493]
When setting the wheel variations with the serverside api (`Vehicle.SetWheelsAsync` in C#) the results are not right. Setting the wheel variations via native (`setVehicleMod` with mod type 23) has a different behaviour (which is the right and expected behaviour).

**Expected behavior**
Setting the wheel variations when using the serverside api and the native should have the same result.

**Current behavior**
The result when setting it serverside and clientside is different.
Example with the `sultan`:

![altV wheels offset](https://user-images.githubusercontent.com/24918879/77940631-47f55c80-72b9-11ea-9a5e-6fc0d8e6fe7e.png)

**Steps to reproduce**
Serverside:
> await vehicle.SetWheelsAsync(0, 1); // Wheel type = Sports | Variation = 1

Clientside:
> game.setVehicleWheelType(localPlayer.vehicle.scriptID, 0); // type = Sports
> game.setVehicleMod(localPlayer.vehicle.scriptID, 23, 1, false); // modType = 23 (Front wheels) | modIndex = 1 | customTires = false

_P.S. The modkit is set!_

**Comment by Lhoerion** [comment]
Not confirmed on `build #1092, branch dev`

I've tested it both on JS & C# server-side. Index differs (natives must have index subtracted by 1 to make it uniform with alt:V API), but that behaviour is intended

**Comment by Hardy535** [comment]
I knew about the offset by 1 but as you can see in the screenshots they weren't.
However I tested it again on the newest dev branch and you are right, this is not happening anymore (code didn't change).
So I guess it was either broken in one build or I had an outdated server that caused this behaviour.
