### ISSUE TITLE
Wrong error message is shown if debug is enabled

### ISSUE THREAD

**Issue by DatMayo** [altmp/altv#509]
When I set `debug=true` in my altv.cfg and connect on a server with `debug=false`, I'm getting the message stored in REFUSED_BY_SERVER. But it should be DEBUG_NOT_ALLOWED

**Expected behavior**
Message in DEBUG_NOT_ALLOWED should be shown

**Current behavior**
Message REFUSED_BY_SERVER is shown

**Possible solution**
Have 2 seperate altv "installs".

**Steps to reproduce**
Set `debug=true` and connect on a `debug=false` server

**Comment by DatMayo** [comment]
As of now, altv shows the correct message.

**Comment by vadzz-dev** [comment]
that happens when server uses CDN
