### ISSUE TITLE
[Bug] Wrong damage

### ISSUE THREAD

**Issue by DimaaIO** [altmp/altv#51]
## Expected Behavior

Damage should be the real damage. --> 35

## Current Behavior

Damage is wrong. --> 65501

## Possible Solution

`ushort realDamage = (ushort)(ushort.MaxValue - fakeDamage + 1);`

## Steps to Reproduce

1. Use the `OnPlayerDamage` event.
1. Injure yourself.

**Comment by vadzz-dev** [comment]
Fixed in latest beta
