### ISSUE TITLE
alt.WebView not opening file upload prompt

### ISSUE THREAD

**Issue by SandDanGlokta** [altmp/altv#511]
Calling ingame a external website (for example a twitter clone) wont allow users to upload images etc using a html form method. Clicking on "upload" wont give the file selector.

**Expected behavior**

**Current behavior**

**Possible solution**

**Steps to reproduce**

**Context (environment)**

**Detailed description**

**Possible implementation**

**Comment by gamelaster** [comment]
For this issue, I think we would need to make our own File Picker Dialog in our UI, since opening Win32 open file dialog would minimize the game I guess. Also, we should wonder about the security of this decision.

**Comment by SandDanGlokta** [comment]
well, 2 others well know multiplayer mods allowed exactly now, whats not possible with altv. so it would be nice, if the guys from altv also would enable the same "function". our players are not able to upload any image at the moment, which is very sad =)

**Comment by SandDanGlokta** [comment]
"open file dialog would minimize the game I guess"
not if you are running gta in windowfullscreen without frames.

**Comment by Revyn112** [comment]
At Meanwhile this is working and should be closed ;)

**Comment by Lhoerion** [comment]
~~Added~~/fixed/~~changed~~ in build #[1180](https://discord.com/channels/371265202378899476/528297438348574741/707678294899687546)
