### ISSUE TITLE
Voice Chat volume

### ISSUE THREAD

**Issue by Lawliz** [altmp/altv#517]
**Current behavior**

The voice chat volume is set with sound effects volume:
![Screenshot_1](https://user-images.githubusercontent.com/31660332/79617903-ed595e80-8108-11ea-94a2-3b4de769c349.png)

But the problem is the vehicles sounds are louder than voice chat volume and if you set it to 0 you can't hear the players.

**Possible solution**

Think it'll be more appropriate in voice chat settings:
![Screenshot_2](https://user-images.githubusercontent.com/31660332/79618012-2db8dc80-8109-11ea-8e12-339f2fbeac7c.png)

**Comment by Lhoerion** [comment]
Does it happen on latest build #1142?

**Comment by Lawliz** [comment]
I'll try it today

**Comment by Lawliz** [comment]
I can't do the test cause the node-module is not up to date on dev branch

**Comment by Lawliz** [comment]
It's good, maybe the spatial is a bit to spatial in parkings but it's really better

**Comment by Lhoerion** [comment]
Added/~fixed~/~changed~ in build #1142
