### ISSUE TITLE
[Bug] LicenseHash different for social club online and offline mode

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv#53]
When connecting to a server (social club version) the license hash _alt.getLicenseHash()_ is different when connecting with offline mode compared when connecting with online mode.

## Expected Behavior
They should be the same for unique identification of the user.

## Current Behavior
They are different, example:
Online: f93ad4e134864617dc3a959a988d61258b533*************************
Offline: e3b0c44298fc1c149afbf4c8996fb92427ae41e*************************

**Comment by emcifuntik** [comment]
Can't be fixed. Social Club ID = 0 in offlineMode. licenseHash in offlineMode always the same
