### ISSUE TITLE
Wrong key code returned for AltGr in key input events

### ISSUE THREAD

**Issue by R0ckzo0r** [altmp/altv#531]
**Expected behavior**
ALT GR should be KeyCode 18, instead its 17

**Steps to reproduce**
Make a Keyup or Keydown on KeyCode 17, ALT GR will trigger it also

**Comment by Lhoerion** [comment]
Windows internally translates `AltGr` to `Ctrl+Alt`, so basically you'll receive two events `Ctrl` & `Alt` separately.

**Comment by Lhoerion** [comment]
Issue closed because of the specified reasons.
Feel free to respond back here, if you think that issue should be reopened.
