### ISSUE TITLE
blip.destroy() does not reset blips value

### ISSUE THREAD

**Issue by GangstaSunny** [altmp/altv#536]
The function blip.destroy() will destroy the blip, but do not set its value back to "undefined" which has do be done my myself. There will still be an object inside the blip.

**Expected behavior**

Reset the destroyed blips value to "undefined"

**Current behavior**

Destroys the blip but 

**Possible solution**

**Steps to reproduce**
- Use blip.destroy
- Use blip.destroy again
       > It will tell you that the entity is "invalid" but not "undefined"

**Comment by FabianTerhorst** [comment]
Thats how it is by design. The value won't just magically go null. It is set internally to not valid.
