### ISSUE TITLE
GameEntityDestroy event not triggered when a player changes dimension

### ISSUE THREAD

**Issue by lameule123** [altmp/altv#537]
**Expected behavior**
GameEntityDestroy/GameEntityCreate should be trigger since player disappear when changing dimension.

**Current behavior**
Event are not trigger.

**Steps to reproduce**
U need a second player to test it.
Place u'rself infront of other player, change dimension of him.

GameEntityDestroy is not trigger when player disappear.

**Comment by lameule123** [comment]
This bug is still here after v1181 release.
Easy to reproduce.

**Comment by vadzz-dev** [comment]
It always triggers for me

**Comment by lameule123** [comment]
I've found an error in my code.
The bug doesn't seem to be present anymore in v1181.
