### ISSUE TITLE
[Bug] Serverside blip creation not working

### ISSUE THREAD

**Issue by datWeazel** [altmp/altv#54]
Creating a blip on serverside creates all blips at coordinates (0,0,0).
I am using the C# API but Heron said that this is probably a SDK issue.

`IBlip blip = Alt.CreateBlip(blipType, position);`
Creates a blip at (0,0,0) and not at the given position.
position != new Position(0,0,0);

## Expected Behavior
Blips should be show at the given position.

## Current Behavior
Blips are shown at (0,0,0) on the map.

## Possible Solution
-//-

## Steps to Reproduce
`Alt.Log("Position: " + position.ToString());
IBlip blip = Alt.CreateBlip(blipType, position);`

## Context (Environment)
Using the C# API with Server on Windows 10.

**Comment by 7Hazard** [comment]
Well it should be reported on the C#'s API, and if the maintainers confirm that it is an issue from the module-api, they should confirm it here.

**Comment by 7Hazard** [comment]
Confirmed, SDK does not set the proper positions, always to 0, 0, 0.

**Comment by vadzz-dev** [comment]
Works on latest beta
