### ISSUE TITLE
[Feature] Online and Offline Mode Parameter

### ISSUE THREAD

**Issue by DasChaosAT** [altmp/altv#62]
**Is your feature request related to a problem? Please describe.**
The License Hash differs between Online and Offline Mode

**Describe the solution you'd like**
If the player has a propertie like IsInOfflineMode you can say wich Hash is used.

**Describe alternatives you've considered**
Only one License Hash for Online and Offline Mode

**Additional context**
Should be clear.

**Comment by Hardy535** [comment]
Related: https://github.com/altmp/altv/issues/53

**Comment by emcifuntik** [comment]
Can't be fixed. Social Club ID = 0 in offlineMode. licenseHash in offlineMode always the same
