### ISSUE TITLE
[FeatureRequest] Add function!

### ISSUE THREAD

**Issue by SuchYMonster** [altmp/altv#64]
I have suggestions to add a function blocking the actions of a given button.

Example: 

P = Map
And i want to block this action.

**Comment by derRAV3N** [comment]
game.disableControlAction(groupId[0-2], actionId[0-360+], true) does this, there is also a list of controls in ragemp wiki which helps a bit finding the right id.

**Comment by Stuyk** [comment]
derRAV3N Is correct on this issue. This can be done on client-side entirely.
