### ISSUE TITLE
[Feature] Allow audio input to be looped back to own audio output

### ISSUE THREAD

**Issue by derRAV3N** [altmp/altv#66]
In addition to issue #65 it would be great to be able to enable a selected audio input device to be looped back to your own selected sound output device so that when using software to play audio effects in voice, you are able to hear them as well, not just players surrounding you.

This could be realized as a checkbox in audio settings on the selected audio input device. When checked, you hear all audio from that selected device locally.

This is part of the other issue #65 just created, and probably doesn't make much sense without it, because even if you play audio effects and your voice on **one** device, you'll hear your own voice, which is not really enjoyable.

**Comment by emcifuntik** [comment]
We already have this feature.

**Comment by derRAV3N** [comment]
How is it used then? Or is it just not implemented in UI?

**Comment by emcifuntik** [comment]
> How is it used then? Or is it just not implemented in UI?

It's not in UI. Check client bindings in `scripts` folder

**Comment by emcifuntik** [comment]
alt.enableVoiceTest will enable voice echo

**Comment by derRAV3N** [comment]
Ah, alright. Maybe this should be implemented in the alt:V client-config in the future? But also, I just remembered that you can select to echo an input device to an output device via windows settings, so this should be irrelevant anyway.
