### ISSUE TITLE
[Feature] Fixing RAGE prop spawn bug.

### ISSUE THREAD

**Issue by DasChaosAT** [altmp/altv#70]
**Is your feature request related to a problem? Please describe.**
If y prop has low priority and vfx, sound or other effects on it, RAGE doesn't spawn the objects. These objects would increase the ambiance a lot. This Bug also appears in Singleplayer and online, so it isn't something alt-v related.

**Describe the solution you'd like**
"just" fixing the bug

**Describe alternatives you've considered**
Not fixing it

**Additional context**
https://gtaforums.com/topic/919609-relv-v-proprestore/

**Comment by Hardy535** [comment]
Here is another approch to fix this by using an ASI (instead of replacing all props to fix the priorities): https://www.gta5-mods.com/scripts/low-priority-prop-restore

**Comment by emcifuntik** [comment]
![image](https://user-images.githubusercontent.com/4309694/57572060-87575800-741e-11e9-8094-c50b41684f2c.png)
Fixed in Build#514
