### ISSUE TITLE
[Bug] Serverside Event "playerDisconnect" loosing Entity

### ISSUE THREAD

**Issue by ripkens** [altmp/altv#87]
## Expected Behavior
The player Object should be available until the Event procedure is finished.

## Current Behavior
The Player Object in the Event gets deleted during the Event procedure
Result: Uncaught Error: entity is invalid

The Events receives the player Object and can access it. But while working with the object (Saving data to Database, running emits to other Clients), player object gets deleted by the Server and further access results in error

## Possible Solution
Maybe just wait 5 Seconds before deleting the Object to have all playerDisconnect Events finished before deleting.

## Context (Environment)
Server: NodeJS

**Comment by FabianTerhorst** [comment]
You have to copy the data out of the entity before running into a async io.
