### ISSUE TITLE
[Bug] game.setPedComponentVariation

### ISSUE THREAD

**Issue by R0ckzo0r** [altmp/altv#89]
## Expected Behavior
game.setPedComponentVariation(alt.playerPedId(),8,0,255,0);

Undershirt Drawable 0 with Texture 255 should be invalid and not set nor visible to other clients in sync. It only effects other players, the localplayer is set correct and has no undershirt visible.

## Current Behavior
game.setPedComponentVariation(alt.playerPedId(),8,0,255,0); is not "streamed" to other players.

## Possible Solution
dunno.

## Steps to Reproduce
set it on clientside, the other player will see a randomTexture of that Undershirt, still 255 should be invalid and not set nor visible.

**Comment by emcifuntik** [comment]
game.setPedComponentVariation(alt.playerPedId(),8,0,240,0);
