### ISSUE TITLE
[Bug] [#543] Rotation is calculated incorrectly

### ISSUE THREAD

**Issue by tmcyrix** [altmp/altv#90]
## Expected Behavior
I expect the vehicle to the right parking position with the exact rotation that has been saved.

## Current Behavior
The getter returns the correct values for the rotation and the setter is setting the correct values for the rotation but the rotation of the vehicle isnt right,

## Possible Solution
No Solution found.

## Steps to Reproduce
1. Create an Vehicle serverside
2. Move it to a different position with a different rotation.
3. Save over the getter the current position and rotation.
4. When starting the server, create the vehicle with the previously saved position and rotation.
5. Go the vehicle and you will see that the position is correctly but the rotation isnt correct.

**Comment by Enerv** [comment]
You can temporarily solve the problem using  client-side natives `setEntityHeading()`.

### Client-side:
```js
alt.onServer('setEntityHeading', (entity, heading) => {
    game.setEntityHeading(entity.scriptID, heading);
});
```
### Server-side:
```js
alt.emitClient(null, 'setEntityHeading', vehicle, 90);
```
I tested it and it's working for me fine.

**Comment by 7Hazard** [comment]
![](https://i.imgur.com/SsiOkLd.jpg)

Adder has rotation 0 while buzzard has PI

The serverside rotations are in radians and they are correct
