### ISSUE TITLE
[Bug] Vehicle mod doesn't exist / doesn't work

### ISSUE THREAD

**Issue by Enerv** [altmp/altv#92]
~Cannot put modifications on vehicles in any way~. It's works.

## Expected Behavior
The function should work in an easy way to give modifications to the vehicle. As in RAGE or GTMP.

## Current Behavior
~Nothing happens~. I try use `game.setVehicleModKit(vehicle, 0);` on client side, `vehicle.modKit = 0;` and `vehicle.setMod(1, 0);` on server side for example and other else types and index but still is nothing happens.

## Possible Solution
I found a solution, thanks Mafia.

```js
vehicle.modKit = 1; // Must be set on 1. If else mod does not work.
vehicle.setMod(0, 2); // Must be a valid type and index. For Blista there is no spoilers.
```

**Comment by targaryen94** [comment]
Hey, how to fixed problem?
