### ISSUE TITLE
[Bug] localPlayer get dimension always 0 in client side

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#94]
If I get localPlayer.dimension in client-side, return value always 0.

Server-side is good.

vehicle.dimension (https://github.com/altmp/altv/issues/75) is also buggy. :(

**Comment by vadzz-dev** [comment]
Yeah, dimension getters do not work clientside

**Comment by FabianTerhorst** [comment]
Does a usecase exists for this? Because only entities in same dimension should be streamed in.
