### ISSUE TITLE
[Bug] Setting Position gives 100% Health.

### ISSUE THREAD

**Issue by GangstaSunny** [altmp/altv#97]
## Expected Behavior
After setting the position, the player should stick to his health he got before the new position was set.

## Current Behavior
After the players position has been changed, the players health will instantly raise to 100%.

## Possible Solution
-

## Steps to Reproduce
Just use "player.position" - Both JS and C#.

**Comment by yoranjj** [comment]
It also revives the player if he's dead.

**Comment by emcifuntik** [comment]
Fixed
